export type Language = 'en' | 'fr' | 'es';

export const LANGUAGE_OPTIONS: { code: Language; short: string; label: string }[] = [
  { code: 'en', short: 'EN', label: 'English' },
  { code: 'fr', short: 'FR', label: 'Français' },
  { code: 'es', short: 'ES', label: 'Español' },
];

export const LANDING_COPY = {
  en: {
    meta: {
      title: 'BuildTrack — Construction, connected from end to end',
      description: 'Plans, issues, teams, inventory and reports in one construction management platform, on mobile and web.',
    },
    accessibility: { skip: 'Skip to content', language: 'Language', navigation: 'Main navigation', proof: 'Platform advantages', openMenu: 'Open menu', closeMenu: 'Close menu' },
    nav: { product: 'Product', roles: 'Roles', reliability: 'Reliability', faq: 'FAQ', login: 'Log in', demo: 'Request a demo' },
    hero: {
      signal: 'The construction operations platform',
      before: 'Nothing gets lost between ',
      highlight: 'the field',
      after: ' and the office.',
      lead: 'BuildTrack brings plans, issues, teams, inventory and reports into one workflow — on mobile, tablet and web.',
      primary: 'See BuildTrack in action',
      secondary: 'Explore the platform',
      assurance: ['Roll out one project at a time', 'Permissions tailored to every role'],
    },
    mock: {
      aria: 'Preview of BuildTrack on desktop and mobile',
      address: 'app.buildtrack.com / project-horizon',
      synced: 'Synced',
      project: 'Project Horizon',
      greeting: 'Hello, Clara.',
      progress: 'Progress',
      openIssues: 'Open issues',
      priorityIssues: '8 high priority',
      teamsOnSite: 'Teams on site',
      companies: '6 companies',
      level: 'Level 2',
      executionPlan: 'Construction plan',
      toHandle: 'To address',
      viewAll: 'View all',
      issueOne: 'Waterproofing repair',
      issueOneMeta: 'Terrace · Due tomorrow',
      issueTwo: 'Fire door adjustment',
      issueTwoMeta: 'Level 2 · Delta Company',
      thisWeek: 'This week',
      valid: 'Approved',
      stockEntry: 'Stock receipt',
      recognized: 'Product identified',
      product: 'DN25 brass valve',
      reference: 'Ref. ABC-12580',
      receivedQuantity: 'Quantity received',
      validateEntry: 'Confirm receipt',
      sameData: 'One source, everywhere',
      sameDataDetail: 'Mobile and web update together',
    },
    proof: [
      { title: 'Mobile + Web', text: 'The same information, at the same time.' },
      { title: 'Offline', text: 'Fieldwork continues, even without coverage.' },
      { title: 'Real time', text: 'Every update reaches the right person.' },
      { title: 'Custom roles', text: 'Everyone sees and does only what matters.' },
    ],
    workflow: {
      eyebrow: '01 / One continuous workflow',
      title: ['One field update.', 'No duplicate entry.'],
      text: 'Information captured once powers the action, the follow-up and the report. No break between the people doing the work and the people steering it.',
      steps: [
        { title: 'Capture', text: 'Photo, plan, scan or voice note directly in the field.' },
        { title: 'Assign', text: 'Company, owner, area, priority and due date.' },
        { title: 'Coordinate', text: 'Instant notification and conversation in context.' },
        { title: 'Verify', text: 'Evidence, signature, history and traceable approval.' },
        { title: 'Decide', text: 'Dashboards and reports built from the same data.' },
      ],
    },
    features: {
      plans: {
        index: 'A — Plans & quality',
        title: 'The plan becomes a decision space.',
        text: 'Place an issue exactly where it belongs, attach the evidence and keep every step of its resolution.',
        bullets: ['Annotated PDF plans and positioned markers', 'Issues, handover checks, priorities and deadlines', 'Photos, signatures and complete history'],
        showcaseAria: 'Example of issue tracking on a construction plan',
        level: 'Level 1 · East area',
        count: '18 issues',
        pinThree: '3 issues to address',
        pinEight: '8 issues to address',
        pinValid: 'Approved issues',
        priority: 'High priority',
        issue: 'Terrace waterproofing repair',
        location: 'East area · Delta Company',
        photos: '3 photo proofs',
      },
      field: {
        index: 'B — Field & coordination',
        title: 'Every site day speaks with one voice.',
        text: 'Daily logs, attendance, visits, incidents and messages share the same project context, even when coverage disappears.',
        bullets: ['Photo, text or voice capture on mobile', 'Contextual notifications and conversations', 'Structured reports, ready to share'],
        showcaseAria: 'Example of live field coordination',
        date: 'August 10',
        liveTitle: 'The field, live',
        live: 'Live',
        events: [
          ['31 arrivals checked in', '4 companies on site'],
          ['Daily log updated', 'Technical area · 5 photos'],
          ['Safety report resolved', 'North access secured'],
          ['Inspection visit', 'Report ready to sign'],
        ],
        voice: 'Voice note',
        quote: '“Repair the threshold before Thursday’s handover.”',
        languages: 'Available in EN · FR · ES',
      },
      stock: {
        index: 'C — Inventory & logistics',
        title: 'From scan to real stock in seconds.',
        text: 'The storekeeper scans the reference, verifies the product, enters the quantity and confirms. Stock, destination and history update automatically.',
        bullets: ['Barcode, QR code and label reading', 'Receipts, issues and consumption by area', 'Minimum-level alerts and PDF or Excel exports'],
        showcaseAria: 'Example of the BuildTrack inventory table',
        titleShort: 'Site inventory',
        location: 'Main store',
        scan: 'Scan',
        alert: '4 references to reorder',
        alertDetail: 'minimum level reached',
        columns: ['Reference', 'Product', 'Stock', 'Status'],
        rows: [
          ['ABC-12580', 'DN25 brass valve', '27', 'Available'],
          ['ELC-44102', '20A circuit breaker', '8', 'Low stock'],
          ['PLB-00815', 'PVC elbow Ø100', '64', 'Available'],
        ],
        last: 'Latest movement',
        movement: '+25 · DN25 brass valve',
      },
    },
    advanced: {
      eyebrow: '02 / Connected advanced workflows',
      title: 'Powerful modules that never become silos.',
      text: 'A plan marker can open an issue, start a conversation, enter a visit report and end in a signed document. Every module keeps the project context.',
      modules: [
        ['Plans & issues', 'Positioned markers, annotated PDFs, priorities, deadlines and evidence.'],
        ['Messaging & companies', 'Project channels, direct exchanges and notifications linked to the right action.'],
        ['Visits & handover checks', 'Checklists, attendees, observations, signatures and multilingual reports.'],
        ['Daily log & attendance', 'Workforce, arrivals, site events, progress and daily photo records.'],
        ['Documents & reports', 'Shared files, controlled access and PDF, Excel or CSV exports.'],
        ['Incidents & safety', 'Field reporting, severity, corrective actions and a complete audit trail.'],
      ],
      feedTitle: 'Project activity',
      feedStatus: 'Live',
      feed: [
        ['Issue RSV-204', '3 photos added from the terrace'],
        ['Inspection visit', 'Report signed by 4 attendees'],
        ['# Delta Company', 'Correction ready for verification'],
        ['Daily report', 'PDF generated and shared'],
      ],
      link: 'Explore these workflows in a demo',
    },
    roles: {
      eyebrow: '03 / One platform, several roles',
      title: 'The right interface for the right responsibility.',
      text: 'BuildTrack adapts navigation, data and actions to each role. An administrator can fine-tune every permission, user by user.',
      tabLabel: 'Choose a construction role',
      demoLink: 'See this workflow in a demo',
      today: 'Today',
      profiles: {
        direction: { label: 'Management', title: 'The real portfolio picture, without waiting for the next report.', text: 'Consolidated projects, progress, delays and alerts help you make decisions with current facts.', stat: '12', statLabel: 'projects monitored', accent: 'Portfolio', items: ['Overall progress', 'Risks and delays', 'Consolidated reports'] },
        conducteur: { label: 'Site manager', title: 'Plans, teams and priorities in the same working day.', text: 'Run issues, tasks, visits and companies from the office or directly in the field.', stat: '18', statLabel: 'actions today', accent: 'Project view', items: ['Issues to verify', 'Tasks this week', 'Daily log and visits'] },
        magasinier: { label: 'Storekeeper', title: 'An interface entirely focused on material movements.', text: 'Receipt, issue, scan, low stock and history stay one tap away. Everything else disappears from the menu.', stat: '842', statLabel: 'units available', accent: 'Inventory workspace', items: ['Scan a product', 'Record a movement', 'Prepare purchase orders'] },
        entreprise: { label: 'Subcontractor', title: 'Every company sees exactly what it has to deliver.', text: 'External teams receive their actions, add evidence and follow approvals without accessing internal project data.', stat: '7', statLabel: 'assigned actions', accent: 'Company portal', items: ['Assigned work', 'Correction photos', 'Acknowledgements and signatures'] },
      },
    },
    reliability: {
      eyebrow: '04 / Built for real conditions',
      title: 'The project does not stop when the network does.',
      text: 'BuildTrack keeps actions on the device, syncs them when coverage returns and protects access by project, company and role.',
      points: [
        ['Offline continuity', 'Entries, photos and actions remain available.'],
        ['Controlled synchronization', 'Queues and automatic recovery.'],
        ['Isolated access', 'Permissions, organizations and projects separated.'],
      ],
      showcaseAria: 'Offline synchronization illustration',
      terrain: 'BuildTrack Field',
      queue: [
        ['3 photos', 'Saved on the device'],
        ['Issue RSV-204', 'Correction documented'],
        ['Today’s daily log', 'Draft saved'],
      ],
      ready: 'Ready',
      connected: 'Connection restored',
      synced: '3 items synchronized',
    },
    capabilities: {
      eyebrow: '05 / From first observation to handover',
      title: ['One complete foundation.', 'Not a pile of tools.'],
      text: 'Every module shares the same projects, teams, documents and access rules. Information remains useful instead of scattering.',
      groups: [
        ['Tracking & quality', 'Annotated PDF plans', 'Issues and handover checks', 'Tasks and planning', 'Visits and checklists', 'Signatures and photo evidence'],
        ['Field', 'Construction daily log', 'Team attendance', 'Incidents and safety', 'Voice and translation', 'Offline mode'],
        ['Logistics', 'Stock by reference', 'Barcode, QR and OCR', 'Receipts and issues', 'Minimum-level alerts', 'Consumption by area'],
        ['Management', 'Dashboards', 'PDF and Excel reports', 'Document management', 'Project messaging', 'Per-user permissions'],
      ],
    },
    faq: {
      eyebrow: '06 / Frequently asked questions',
      title: 'Before you launch your first project.',
      text: 'The demo starts with your workflows and roles, not a generic script.',
      items: [
        ['Does BuildTrack work on phones and computers?', 'Yes. Field teams use the mobile app, while office teams work with the same data in the web interface.'],
        ['What happens without coverage on site?', 'Compatible actions are saved locally and synchronized when the network returns. Users can see what is still waiting to send.'],
        ['Can BuildTrack be limited to one role, such as a storekeeper?', 'Yes. Menus and actions adapt to the role. An administrator can then customize permissions for each individual user.'],
        ['Do subcontractors have to see the entire project?', 'No. Their portal can be limited to the actions and documents that concern them, including evidence, tracking and approval.'],
        ['Can the data be exported?', 'Yes. Useful reports and statements can be generated as PDF, Excel or CSV depending on the module: issues, visits, inventory, consumption and tracking.'],
      ],
    },
    demo: {
      eyebrow: 'Your project, your demo',
      title: 'See the right workflow, with the right roles.',
      text: 'Tell us how your organization works. We will show you how BuildTrack connects field teams, companies and management.',
      promises: [
        ['Operational discussion', 'Focused on the way your teams work.'],
        ['Targeted demonstration', 'Only the modules that matter to you.'],
        ['Progressive rollout', 'By project, role or organization.'],
      ],
      formTitle: 'Request a demonstration',
      required: 'Fields marked * are required.',
      name: 'First and last name *',
      namePlaceholder: 'Alex Morgan',
      company: 'Company *',
      companyPlaceholder: 'Your company',
      email: 'Work e-mail *',
      emailPlaceholder: 'alex@company.com',
      phone: 'Phone',
      phonePlaceholder: '+44 20 0000 0000',
      team: 'Team size',
      teamPlaceholder: 'Select a range',
      teamOptions: ['1 to 10 people', '11 to 50 people', '51 to 200 people', 'More than 200 people'],
      need: 'What do you need?',
      needPlaceholder: 'Modules, current organization, number of projects…',
      submit: 'Schedule my demonstration',
      sending: 'Sending…',
      legal: 'Your information is used only to respond to this request.',
      fallbackError: 'Something went wrong. Please try again in a moment.',
      fallbackSuccess: 'Your request has been sent. We will contact you shortly.',
      honeypot: 'Website',
    },
    footer: { tagline: 'Construction, connected from end to end.', platform: 'Platform', access: 'Access', write: 'Contact us', baseline: 'Construction management, mobile and web.' },
  },
  fr: {
    meta: {
      title: 'BuildTrack — Le chantier, relié de bout en bout',
      description: 'Plans, réserves, équipes, stock et rapports réunis dans une seule plateforme de gestion de chantier, sur mobile et sur le web.',
    },
    accessibility: { skip: 'Aller au contenu', language: 'Langue', navigation: 'Navigation principale', proof: 'Atouts de la plateforme', openMenu: 'Ouvrir le menu', closeMenu: 'Fermer le menu' },
    nav: { product: 'Produit', roles: 'Métiers', reliability: 'Fiabilité', faq: 'FAQ', login: 'Se connecter', demo: 'Demander une démo' },
    hero: {
      signal: 'La plateforme opérationnelle du chantier',
      before: 'Rien ne se perd entre ',
      highlight: 'le terrain',
      after: ' et le bureau.',
      lead: 'BuildTrack réunit plans, réserves, équipes, stock et rapports dans un même fil de travail — sur mobile, tablette et web.',
      primary: 'Voir BuildTrack en action',
      secondary: 'Explorer la plateforme',
      assurance: ['Déploiement par chantier', 'Droits adaptés à chaque rôle'],
    },
    mock: {
      aria: 'Aperçu de BuildTrack sur ordinateur et téléphone', address: 'app.buildtrack.fr / projet-horizon', synced: 'Synchronisé', project: 'Projet Horizon', greeting: 'Bonjour, Clara.', progress: 'Avancement', openIssues: 'Réserves ouvertes', priorityIssues: '8 prioritaires', teamsOnSite: 'Équipes présentes', companies: '6 entreprises', level: 'Niveau R+2', executionPlan: 'Plan d’exécution', toHandle: 'À traiter', viewAll: 'Voir tout', issueOne: 'Reprise étanchéité', issueOneMeta: 'Terrasse · Échéance demain', issueTwo: 'Réglage porte coupe-feu', issueTwoMeta: 'R+2 · Entreprise Delta', thisWeek: 'Cette semaine', valid: 'Validé', stockEntry: 'Entrée stock', recognized: 'Produit reconnu', product: 'Vanne laiton DN25', reference: 'Réf. ABC-12580', receivedQuantity: 'Quantité reçue', validateEntry: 'Valider l’entrée', sameData: 'Même donnée, partout', sameDataDetail: 'Mobile et web mis à jour ensemble',
    },
    proof: [
      { title: 'Mobile + Web', text: 'La même information, au même moment.' },
      { title: 'Hors ligne', text: 'Le terrain continue, même sans réseau.' },
      { title: 'Temps réel', text: 'Chaque évolution arrive au bon interlocuteur.' },
      { title: 'Rôles sur mesure', text: 'Chacun voit et fait uniquement le nécessaire.' },
    ],
    workflow: {
      eyebrow: '01 / Un seul fil de travail', title: ['Un mouvement terrain.', 'Pas une double saisie.'], text: 'Une information captée une fois alimente l’action, le suivi et le rapport. Sans rupture entre ceux qui font et ceux qui pilotent.',
      steps: [
        { title: 'Constater', text: 'Photo, plan, scan ou dictée directement sur le terrain.' },
        { title: 'Attribuer', text: 'Entreprise, responsable, zone, priorité et échéance.' },
        { title: 'Coordonner', text: 'Notification immédiate et échange dans le bon contexte.' },
        { title: 'Vérifier', text: 'Preuve, signature, historique et validation traçable.' },
        { title: 'Décider', text: 'Tableau de bord et rapport générés depuis les mêmes données.' },
      ],
    },
    features: {
      plans: { index: 'A — Plans & qualité', title: 'Le plan devient un espace de décision.', text: 'Positionnez une réserve au bon endroit, joignez les preuves et conservez chaque étape de sa résolution.', bullets: ['Plans PDF annotés et repères géolocalisés', 'Réserves, OPR, priorités et échéances', 'Photos, signatures et historique complet'], showcaseAria: 'Exemple de suivi de réserves sur un plan', level: 'Niveau R+1 · Zone Est', count: '18 réserves', pinThree: '3 réserves à traiter', pinEight: '8 réserves à traiter', pinValid: 'Réserves validées', priority: 'Prioritaire', issue: 'Reprise étanchéité terrasse', location: 'Zone Est · Entreprise Delta', photos: '3 preuves photo' },
      field: { index: 'B — Terrain & coordination', title: 'La journée de chantier parle d’une seule voix.', text: 'Journal, pointage, visites, incidents et messagerie partagent le même contexte projet, même lorsque le réseau disparaît.', bullets: ['Saisie photo, texte ou dictée sur mobile', 'Notifications et échanges contextualisés', 'Rapports structurés, prêts à transmettre'], showcaseAria: 'Exemple de coordination des opérations terrain', date: 'Journée du 10 août', liveTitle: 'Le terrain en direct', live: 'En direct', events: [['31 arrivées pointées', '4 entreprises sur site'], ['Journal mis à jour', 'Zone technique · 5 photos'], ['Signalement sécurité traité', 'Accès nord sécurisé'], ['Visite de contrôle', 'Compte rendu prêt à signer']], voice: 'Note dictée', quote: '« Prévoir la reprise du seuil avant la réception de jeudi. »', languages: 'Disponible en FR · EN · ES' },
      stock: { index: 'C — Stock & logistique', title: 'Du scan au stock réel en quelques secondes.', text: 'Le magasinier scanne la référence, vérifie le produit, saisit la quantité et valide. Le stock, la destination et l’historique suivent automatiquement.', bullets: ['Code-barres, QR code et lecture d’étiquette', 'Entrées, sorties et consommation par zone', 'Alertes de seuil et exports PDF ou Excel'], showcaseAria: 'Exemple de tableau de stock BuildTrack', titleShort: 'Stock chantier', location: 'Magasin principal', scan: 'Scanner', alert: '4 références à commander', alertDetail: 'seuil minimum atteint', columns: ['Référence', 'Produit', 'Stock', 'État'], rows: [['ABC-12580', 'Vanne laiton DN25', '27', 'Disponible'], ['ELC-44102', 'Disjoncteur 20A', '8', 'Stock faible'], ['PLB-00815', 'Coude PVC Ø100', '64', 'Disponible']], last: 'Dernier mouvement', movement: '+25 · Vanne laiton DN25' },
    },
    advanced: {
      eyebrow: '02 / Des flux avancés, reliés entre eux',
      title: 'Des modules puissants qui ne deviennent jamais des silos.',
      text: 'Un repère sur plan peut ouvrir une réserve, lancer une conversation, alimenter une visite puis finir dans un document signé. Chaque module conserve le contexte chantier.',
      modules: [
        ['Plans & réserves', 'Repères positionnés, PDF annotés, priorités, échéances et preuves.'],
        ['Messagerie & entreprises', 'Canaux projet, échanges directs et notifications liées à la bonne action.'],
        ['Visites & OPR', 'Check-lists, participants, observations, signatures et rapports multilingues.'],
        ['Journal & pointage', 'Effectifs, arrivées, événements, avancement et relevé photo quotidien.'],
        ['Documents & rapports', 'Fichiers partagés, accès maîtrisés et exports PDF, Excel ou CSV.'],
        ['Incidents & sécurité', 'Signalement terrain, gravité, actions correctives et historique complet.'],
      ],
      feedTitle: 'Activité du chantier',
      feedStatus: 'En direct',
      feed: [
        ['Réserve RSV-204', '3 photos ajoutées depuis la terrasse'],
        ['Visite de contrôle', 'Compte rendu signé par 4 participants'],
        ['# Entreprise Delta', 'Correction prête à être vérifiée'],
        ['Rapport journalier', 'PDF généré et partagé'],
      ],
      link: 'Explorer ces parcours en démonstration',
    },
    roles: {
      eyebrow: '03 / Une plateforme, plusieurs métiers', title: 'La bonne interface pour la bonne responsabilité.', text: 'BuildTrack adapte navigation, données et actions au rôle. Un administrateur peut encore affiner chaque droit utilisateur par utilisateur.', tabLabel: 'Choisir un profil métier', demoLink: 'Voir ce parcours en démonstration', today: 'Aujourd’hui',
      profiles: {
        direction: { label: 'Direction', title: 'La réalité du portefeuille, sans attendre le prochain compte rendu.', text: 'Vue consolidée des chantiers, indicateurs d’avancement, retards et alertes pour arbitrer sur des faits à jour.', stat: '12', statLabel: 'chantiers suivis', accent: 'Portefeuille', items: ['Avancement global', 'Risques et retards', 'Rapports consolidés'] },
        conducteur: { label: 'Conducteur', title: 'Plans, équipes et priorités réunis dans la même journée de travail.', text: 'Pilotez les réserves, tâches, visites et entreprises depuis le bureau comme depuis le terrain.', stat: '18', statLabel: 'actions aujourd’hui', accent: 'Vue chantier', items: ['Réserves à vérifier', 'Tâches de la semaine', 'Journal et visites'] },
        magasinier: { label: 'Magasinier', title: 'Une interface entièrement centrée sur les mouvements de matériel.', text: 'Entrée, sortie, scan, stock faible et historique restent immédiatement accessibles. Le reste de BuildTrack disparaît du menu.', stat: '842', statLabel: 'unités disponibles', accent: 'Poste stock', items: ['Scanner un produit', 'Enregistrer un mouvement', 'Préparer les commandes'] },
        entreprise: { label: 'Sous-traitant', title: 'Chaque entreprise voit exactement ce qu’elle doit traiter.', text: 'Les équipes externes reçoivent leurs actions, ajoutent leurs preuves et suivent les validations sans accéder aux données internes.', stat: '7', statLabel: 'actions assignées', accent: 'Portail entreprise', items: ['Travaux assignés', 'Photos de correction', 'Accusés et signatures'] },
      },
    },
    reliability: { eyebrow: '04 / Conçu pour le réel', title: 'Le chantier ne s’arrête pas à cause du réseau.', text: 'BuildTrack conserve les actions sur l’appareil, les synchronise dès que la connexion revient et protège l’accès selon le projet, l’entreprise et le rôle.', points: [['Continuité hors ligne', 'Saisie, photos et actions restent disponibles.'], ['Synchronisation maîtrisée', 'Files d’attente et reprise automatique.'], ['Accès cloisonnés', 'Droits, organisations et projets isolés.']], showcaseAria: 'Illustration de la synchronisation hors ligne', terrain: 'BuildTrack Terrain', queue: [['3 photos', 'Enregistrées sur l’appareil'], ['Réserve RSV-204', 'Correction documentée'], ['Journal du jour', 'Brouillon sauvegardé']], ready: 'Prêt', connected: 'Connexion retrouvée', synced: '3 éléments synchronisés' },
    capabilities: { eyebrow: '05 / Du premier constat au DOE', title: ['Un socle complet.', 'Pas un empilement d’outils.'], text: 'Chaque module partage les mêmes projets, équipes, documents et règles d’accès. L’information reste exploitable au lieu de se disperser.', groups: [['Suivi & qualité', 'Plans PDF annotés', 'Réserves et OPR', 'Tâches et planning', 'Visites et check-lists', 'Signatures et preuves photo'], ['Terrain', 'Journal de chantier', 'Pointage équipes', 'Incidents et sécurité', 'Dictée et traduction', 'Mode hors ligne'], ['Logistique', 'Stock par référence', 'Code-barres, QR et OCR', 'Entrées et sorties', 'Seuils d’alerte', 'Consommation par zone'], ['Pilotage', 'Tableaux de bord', 'Rapports PDF et Excel', 'Gestion documentaire', 'Messagerie projet', 'Droits par utilisateur']] },
    faq: { eyebrow: '06 / Questions fréquentes', title: 'Avant de lancer votre premier chantier.', text: 'La démonstration part de vos usages et de vos profils, pas d’un scénario générique.', items: [['BuildTrack fonctionne-t-il sur téléphone et sur ordinateur ?', 'Oui. Les équipes terrain utilisent l’application mobile et les équipes bureau retrouvent les mêmes données sur l’interface web.'], ['Que se passe-t-il sans connexion sur le chantier ?', 'Les actions compatibles sont conservées localement puis synchronisées lorsque le réseau revient. L’utilisateur voit ce qui attend encore l’envoi.'], ['Peut-on limiter BuildTrack à un seul métier, comme le magasinier ?', 'Oui. Le menu et les actions s’adaptent au rôle. Les droits peuvent ensuite être personnalisés par un administrateur pour chaque utilisateur.'], ['Les sous-traitants doivent-ils voir tout le chantier ?', 'Non. Leur portail peut être limité aux actions et documents qui les concernent, avec ajout de preuves, suivi et validation.'], ['Peut-on exporter les données ?', 'Oui. Les rapports et états utiles peuvent être générés en PDF, Excel ou CSV selon le module : réserves, visites, stock, consommations et suivi.']] },
    demo: { eyebrow: 'Votre chantier, votre démonstration', title: 'Voyez le bon parcours, avec les bons rôles.', text: 'Expliquez-nous votre organisation. Nous vous montrons comment BuildTrack relie vos équipes terrain, vos entreprises et votre pilotage.', promises: [['Échange opérationnel', 'Centré sur votre manière de travailler.'], ['Démonstration ciblée', 'Uniquement les modules utiles à vos équipes.'], ['Déploiement progressif', 'Par chantier, métier ou organisation.']], formTitle: 'Demander une démonstration', required: 'Les champs marqués * sont obligatoires.', name: 'Prénom et nom *', namePlaceholder: 'Camille Martin', company: 'Entreprise *', companyPlaceholder: 'Votre entreprise', email: 'E-mail professionnel *', emailPlaceholder: 'camille@entreprise.fr', phone: 'Téléphone', phonePlaceholder: '+33 6 00 00 00 00', team: 'Taille de l’équipe', teamPlaceholder: 'Sélectionner une plage', teamOptions: ['1 à 10 personnes', '11 à 50 personnes', '51 à 200 personnes', 'Plus de 200 personnes'], need: 'Votre besoin', needPlaceholder: 'Modules recherchés, organisation actuelle, nombre de chantiers…', submit: 'Planifier ma démonstration', sending: 'Envoi en cours…', legal: 'Vos informations sont utilisées uniquement pour répondre à cette demande.', fallbackError: 'Une erreur est survenue. Réessayez dans un instant.', fallbackSuccess: 'Votre demande est bien partie. Nous vous recontactons rapidement.', honeypot: 'Site internet' },
    footer: { tagline: 'Le chantier, relié de bout en bout.', platform: 'Plateforme', access: 'Accès', write: 'Nous écrire', baseline: 'Gestion de chantier, mobile et web.' },
  },
  es: {
    meta: {
      title: 'BuildTrack — La obra, conectada de principio a fin',
      description: 'Planos, reservas, equipos, stock e informes en una sola plataforma de gestión de obra, en móvil y web.',
    },
    accessibility: { skip: 'Ir al contenido', language: 'Idioma', navigation: 'Navegación principal', proof: 'Ventajas de la plataforma', openMenu: 'Abrir menú', closeMenu: 'Cerrar menú' },
    nav: { product: 'Producto', roles: 'Perfiles', reliability: 'Fiabilidad', faq: 'Preguntas', login: 'Iniciar sesión', demo: 'Solicitar una demo' },
    hero: { signal: 'La plataforma operativa de la obra', before: 'Nada se pierde entre ', highlight: 'la obra', after: ' y la oficina.', lead: 'BuildTrack reúne planos, reservas, equipos, stock e informes en un mismo flujo de trabajo — en móvil, tableta y web.', primary: 'Ver BuildTrack en acción', secondary: 'Explorar la plataforma', assurance: ['Despliegue por obra', 'Permisos adaptados a cada perfil'] },
    mock: { aria: 'Vista previa de BuildTrack en ordenador y teléfono', address: 'app.buildtrack.com / proyecto-horizonte', synced: 'Sincronizado', project: 'Proyecto Horizonte', greeting: 'Hola, Clara.', progress: 'Avance', openIssues: 'Reservas abiertas', priorityIssues: '8 prioritarias', teamsOnSite: 'Equipos presentes', companies: '6 empresas', level: 'Nivel 2', executionPlan: 'Plano de ejecución', toHandle: 'Por resolver', viewAll: 'Ver todo', issueOne: 'Reparar impermeabilización', issueOneMeta: 'Terraza · Vence mañana', issueTwo: 'Ajustar puerta cortafuegos', issueTwoMeta: 'Nivel 2 · Empresa Delta', thisWeek: 'Esta semana', valid: 'Validado', stockEntry: 'Entrada de stock', recognized: 'Producto identificado', product: 'Válvula de latón DN25', reference: 'Ref. ABC-12580', receivedQuantity: 'Cantidad recibida', validateEntry: 'Validar entrada', sameData: 'El mismo dato, en todas partes', sameDataDetail: 'Móvil y web se actualizan juntos' },
    proof: [{ title: 'Móvil + Web', text: 'La misma información, al mismo tiempo.' }, { title: 'Sin conexión', text: 'La obra continúa, incluso sin cobertura.' }, { title: 'Tiempo real', text: 'Cada cambio llega a la persona adecuada.' }, { title: 'Perfiles a medida', text: 'Cada uno ve y hace solo lo necesario.' }],
    workflow: { eyebrow: '01 / Un único flujo de trabajo', title: ['Un movimiento en obra.', 'Sin duplicar datos.'], text: 'La información registrada una vez alimenta la acción, el seguimiento y el informe. Sin ruptura entre quienes ejecutan y quienes dirigen.', steps: [{ title: 'Registrar', text: 'Foto, plano, escaneo o dictado directamente en obra.' }, { title: 'Asignar', text: 'Empresa, responsable, zona, prioridad y fecha.' }, { title: 'Coordinar', text: 'Aviso inmediato y conversación con contexto.' }, { title: 'Verificar', text: 'Evidencia, firma, historial y validación trazable.' }, { title: 'Decidir', text: 'Paneles e informes generados con los mismos datos.' }] },
    features: {
      plans: { index: 'A — Planos y calidad', title: 'El plano se convierte en un espacio de decisión.', text: 'Sitúa una reserva en el lugar exacto, adjunta las evidencias y conserva cada etapa de su resolución.', bullets: ['Planos PDF anotados y marcadores posicionados', 'Reservas, OPR, prioridades y plazos', 'Fotos, firmas e historial completo'], showcaseAria: 'Ejemplo de seguimiento de reservas en un plano', level: 'Nivel 1 · Zona Este', count: '18 reservas', pinThree: '3 reservas por resolver', pinEight: '8 reservas por resolver', pinValid: 'Reservas validadas', priority: 'Prioritaria', issue: 'Reparar impermeabilización de terraza', location: 'Zona Este · Empresa Delta', photos: '3 evidencias fotográficas' },
      field: { index: 'B — Obra y coordinación', title: 'Toda la jornada de obra habla con una sola voz.', text: 'Diario, asistencia, visitas, incidencias y mensajes comparten el mismo contexto de proyecto, incluso cuando desaparece la cobertura.', bullets: ['Captura por foto, texto o voz en el móvil', 'Avisos y conversaciones con contexto', 'Informes estructurados, listos para compartir'], showcaseAria: 'Ejemplo de coordinación de obra en directo', date: 'Jornada del 10 de agosto', liveTitle: 'La obra en directo', live: 'En directo', events: [['31 llegadas registradas', '4 empresas en obra'], ['Diario actualizado', 'Zona técnica · 5 fotos'], ['Aviso de seguridad resuelto', 'Acceso norte asegurado'], ['Visita de control', 'Informe listo para firmar']], voice: 'Nota dictada', quote: '« Reparar el umbral antes de la recepción del jueves. »', languages: 'Disponible en ES · EN · FR' },
      stock: { index: 'C — Stock y logística', title: 'Del escaneo al stock real en segundos.', text: 'El almacenero escanea la referencia, verifica el producto, introduce la cantidad y valida. El stock, el destino y el historial se actualizan automáticamente.', bullets: ['Código de barras, QR y lectura de etiquetas', 'Entradas, salidas y consumo por zona', 'Alertas de mínimo y exportación PDF o Excel'], showcaseAria: 'Ejemplo de tabla de stock de BuildTrack', titleShort: 'Stock de obra', location: 'Almacén principal', scan: 'Escanear', alert: '4 referencias por pedir', alertDetail: 'mínimo alcanzado', columns: ['Referencia', 'Producto', 'Stock', 'Estado'], rows: [['ABC-12580', 'Válvula de latón DN25', '27', 'Disponible'], ['ELC-44102', 'Interruptor 20A', '8', 'Stock bajo'], ['PLB-00815', 'Codo PVC Ø100', '64', 'Disponible']], last: 'Último movimiento', movement: '+25 · Válvula de latón DN25' },
    },
    advanced: {
      eyebrow: '02 / Flujos avanzados conectados',
      title: 'Módulos potentes que nunca se convierten en silos.',
      text: 'Un marcador del plano puede abrir una reserva, iniciar una conversación, alimentar una visita y terminar en un documento firmado. Cada módulo conserva el contexto de la obra.',
      modules: [
        ['Planos y reservas', 'Marcadores, PDF anotados, prioridades, plazos y evidencias.'],
        ['Mensajería y empresas', 'Canales de proyecto, conversaciones directas y avisos ligados a cada acción.'],
        ['Visitas y OPR', 'Listas, participantes, observaciones, firmas e informes multilingües.'],
        ['Diario y asistencia', 'Personal, llegadas, eventos, avance y registro fotográfico diario.'],
        ['Documentos e informes', 'Archivos compartidos, accesos controlados y exportación PDF, Excel o CSV.'],
        ['Incidencias y seguridad', 'Avisos de obra, gravedad, acciones correctivas e historial completo.'],
      ],
      feedTitle: 'Actividad de la obra',
      feedStatus: 'En directo',
      feed: [
        ['Reserva RSV-204', '3 fotos añadidas desde la terraza'],
        ['Visita de control', 'Informe firmado por 4 participantes'],
        ['# Empresa Delta', 'Corrección lista para verificar'],
        ['Informe diario', 'PDF generado y compartido'],
      ],
      link: 'Explorar estos flujos en una demostración',
    },
    roles: { eyebrow: '03 / Una plataforma, varios perfiles', title: 'La interfaz adecuada para cada responsabilidad.', text: 'BuildTrack adapta la navegación, los datos y las acciones al perfil. Un administrador puede ajustar cada permiso usuario por usuario.', tabLabel: 'Elegir un perfil de obra', demoLink: 'Ver este flujo en una demostración', today: 'Hoy', profiles: {
      direction: { label: 'Dirección', title: 'La realidad de la cartera, sin esperar al próximo informe.', text: 'Vista consolidada de obras, avance, retrasos y alertas para decidir con datos actuales.', stat: '12', statLabel: 'obras supervisadas', accent: 'Cartera', items: ['Avance global', 'Riesgos y retrasos', 'Informes consolidados'] },
      conducteur: { label: 'Jefe de obra', title: 'Planos, equipos y prioridades en la misma jornada de trabajo.', text: 'Gestiona reservas, tareas, visitas y empresas desde la oficina o directamente en obra.', stat: '18', statLabel: 'acciones hoy', accent: 'Vista de obra', items: ['Reservas por verificar', 'Tareas de la semana', 'Diario y visitas'] },
      magasinier: { label: 'Almacenero', title: 'Una interfaz centrada por completo en los movimientos de material.', text: 'Entrada, salida, escaneo, stock bajo e historial quedan a un toque. El resto de BuildTrack desaparece del menú.', stat: '842', statLabel: 'unidades disponibles', accent: 'Puesto de almacén', items: ['Escanear un producto', 'Registrar un movimiento', 'Preparar pedidos'] },
      entreprise: { label: 'Subcontrata', title: 'Cada empresa ve exactamente lo que debe resolver.', text: 'Los equipos externos reciben sus acciones, añaden evidencias y siguen las validaciones sin acceder a los datos internos.', stat: '7', statLabel: 'acciones asignadas', accent: 'Portal de empresa', items: ['Trabajos asignados', 'Fotos de corrección', 'Acuses y firmas'] },
    } },
    reliability: { eyebrow: '04 / Diseñado para la realidad', title: 'La obra no se detiene cuando falla la red.', text: 'BuildTrack conserva las acciones en el dispositivo, las sincroniza al recuperar cobertura y protege el acceso por proyecto, empresa y perfil.', points: [['Continuidad sin conexión', 'Datos, fotos y acciones siguen disponibles.'], ['Sincronización controlada', 'Colas y recuperación automática.'], ['Accesos aislados', 'Permisos, organizaciones y proyectos separados.']], showcaseAria: 'Ilustración de la sincronización sin conexión', terrain: 'BuildTrack Obra', queue: [['3 fotos', 'Guardadas en el dispositivo'], ['Reserva RSV-204', 'Corrección documentada'], ['Diario de hoy', 'Borrador guardado']], ready: 'Listo', connected: 'Conexión recuperada', synced: '3 elementos sincronizados' },
    capabilities: { eyebrow: '05 / Desde la primera observación hasta la entrega', title: ['Una base completa.', 'No una suma de herramientas.'], text: 'Todos los módulos comparten proyectos, equipos, documentos y reglas de acceso. La información sigue siendo útil en lugar de dispersarse.', groups: [['Seguimiento y calidad', 'Planos PDF anotados', 'Reservas y OPR', 'Tareas y planificación', 'Visitas y listas de control', 'Firmas y evidencias fotográficas'], ['Obra', 'Diario de obra', 'Control de asistencia', 'Incidencias y seguridad', 'Dictado y traducción', 'Modo sin conexión'], ['Logística', 'Stock por referencia', 'Código de barras, QR y OCR', 'Entradas y salidas', 'Alertas de mínimo', 'Consumo por zona'], ['Dirección', 'Paneles de control', 'Informes PDF y Excel', 'Gestión documental', 'Mensajería de proyecto', 'Permisos por usuario']] },
    faq: { eyebrow: '06 / Preguntas frecuentes', title: 'Antes de lanzar tu primera obra.', text: 'La demostración parte de tus procesos y perfiles, no de un guion genérico.', items: [['¿BuildTrack funciona en teléfono y ordenador?', 'Sí. Los equipos de obra usan la aplicación móvil y la oficina trabaja con los mismos datos en la interfaz web.'], ['¿Qué ocurre cuando no hay cobertura en la obra?', 'Las acciones compatibles se guardan localmente y se sincronizan cuando vuelve la red. El usuario ve lo que aún está pendiente de envío.'], ['¿Se puede limitar BuildTrack a un solo perfil, como el almacenero?', 'Sí. El menú y las acciones se adaptan al perfil. Después, un administrador puede personalizar los permisos de cada usuario.'], ['¿Las subcontratas tienen que ver toda la obra?', 'No. Su portal puede limitarse a las acciones y documentos que les conciernen, con evidencias, seguimiento y validación.'], ['¿Se pueden exportar los datos?', 'Sí. Los informes y estados útiles pueden generarse en PDF, Excel o CSV según el módulo: reservas, visitas, stock, consumo y seguimiento.']] },
    demo: { eyebrow: 'Tu obra, tu demostración', title: 'Mira el flujo adecuado, con los perfiles adecuados.', text: 'Cuéntanos cómo funciona tu organización. Te mostraremos cómo BuildTrack conecta los equipos de obra, las empresas y la dirección.', promises: [['Conversación operativa', 'Centrada en la forma de trabajar de tus equipos.'], ['Demostración específica', 'Solo los módulos que realmente necesitas.'], ['Despliegue progresivo', 'Por obra, perfil u organización.']], formTitle: 'Solicitar una demostración', required: 'Los campos marcados con * son obligatorios.', name: 'Nombre y apellidos *', namePlaceholder: 'Alex García', company: 'Empresa *', companyPlaceholder: 'Tu empresa', email: 'E-mail profesional *', emailPlaceholder: 'alex@empresa.es', phone: 'Teléfono', phonePlaceholder: '+34 600 000 000', team: 'Tamaño del equipo', teamPlaceholder: 'Selecciona un rango', teamOptions: ['1 a 10 personas', '11 a 50 personas', '51 a 200 personas', 'Más de 200 personas'], need: '¿Qué necesitas?', needPlaceholder: 'Módulos, organización actual, número de obras…', submit: 'Programar mi demostración', sending: 'Enviando…', legal: 'Tus datos se utilizan únicamente para responder a esta solicitud.', fallbackError: 'Se ha producido un error. Inténtalo de nuevo en un momento.', fallbackSuccess: 'Tu solicitud se ha enviado. Nos pondremos en contacto contigo pronto.', honeypot: 'Sitio web' },
    footer: { tagline: 'La obra, conectada de principio a fin.', platform: 'Plataforma', access: 'Acceso', write: 'Contactar', baseline: 'Gestión de obra, móvil y web.' },
  },
} as const;
