import { inventoryDocumentCopy, type InventoryDocumentLanguage } from './inventoryDocumentCopy';
import {
  inventoryWorkbookBytesToBase64,
  type InventoryWorkbookMovement,
  type InventoryWorkbookProduct,
} from './inventoryWorkbookEngine';

type DocxCell = {
  text?: string | number;
  runs?: Array<{ text: string; bold?: boolean; color?: string; size?: number; italic?: boolean }>;
  paragraphs?: string[];
  align?: 'left' | 'center' | 'right';
  fill?: string;
  color?: string;
  bold?: boolean;
};

export type InventoryDocxZipRuntime = {
  strToU8: (text: string) => Uint8Array;
  zipSync: (
    files: Record<string, Uint8Array>,
    options?: { level?: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 },
  ) => Uint8Array;
};

type DocxLanguageCopy = {
  reportTitle: string;
  executiveSummary: string;
  generatedBy: string;
  confidential: string;
  page: string;
  of: string;
  selectedScope: string;
  latestMovements: string;
  latestMovementsNote: (shown: number, total: number) => string;
};

const DOCX_COPY: Record<InventoryDocumentLanguage, DocxLanguageCopy> = {
  fr: {
    reportTitle: 'Rapport de stock chantier', executiveSummary: 'Synthèse opérationnelle', generatedBy: 'Généré par BuildTrack',
    confidential: 'Document confidentiel', page: 'Page', of: 'sur', selectedScope: 'Périmètre sélectionné',
    latestMovements: 'Derniers mouvements', latestMovementsNote: (shown, total) => `${shown} mouvement(s) affiché(s) sur ${total}.`,
  },
  en: {
    reportTitle: 'Construction inventory report', executiveSummary: 'Operational summary', generatedBy: 'Generated by BuildTrack',
    confidential: 'Confidential document', page: 'Page', of: 'of', selectedScope: 'Selected scope',
    latestMovements: 'Latest movements', latestMovementsNote: (shown, total) => `${shown} movement(s) shown out of ${total}.`,
  },
  es: {
    reportTitle: 'Informe de stock de obra', executiveSummary: 'Resumen operativo', generatedBy: 'Generado por BuildTrack',
    confidential: 'Documento confidencial', page: 'Página', of: 'de', selectedScope: 'Ámbito seleccionado',
    latestMovements: 'Últimos movimientos', latestMovementsNote: (shown, total) => `${shown} movimiento(s) mostrado(s) de ${total}.`,
  },
};

const CONTENT_WIDTH = 14_160;
const BRAND = '0F3B75';
const BRAND_LIGHT = 'EAF1F8';
const TEXT = '17243A';
const MUTED = '64748B';
const BORDER = 'D8E1EC';
const ALT = 'F7F9FC';
const SUCCESS_FILL = 'E8F8F4';
const WARNING_FILL = 'FFF4D6';
const DANGER_FILL = 'FDE8E8';

function xml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function finite(value: unknown): number {
  const parsed = Number(value ?? 0);
  return Number.isFinite(parsed) ? parsed : 0;
}

function formatNumber(value: unknown, locale: string): string {
  return new Intl.NumberFormat(locale, { maximumFractionDigits: 3 }).format(finite(value));
}

function formatDate(value: Date | string | number, locale: string): string {
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return String(value ?? '');
  return new Intl.DateTimeFormat(locale, { dateStyle: 'medium', timeStyle: 'short' }).format(date);
}

function run(
  text: string,
  options: { bold?: boolean; color?: string; size?: number; italic?: boolean } = {},
): string {
  const properties = [
    options.bold ? '<w:b/>' : '',
    options.italic ? '<w:i/>' : '',
    options.color ? `<w:color w:val="${options.color}"/>` : '',
    options.size ? `<w:sz w:val="${options.size}"/><w:szCs w:val="${options.size}"/>` : '',
  ].join('');
  const preserve = /^\s|\s$/.test(text) ? ' xml:space="preserve"' : '';
  return `<w:r>${properties ? `<w:rPr>${properties}</w:rPr>` : ''}<w:t${preserve}>${xml(text)}</w:t></w:r>`;
}

function paragraph(
  content: string | Array<{ text: string; bold?: boolean; color?: string; size?: number; italic?: boolean }>,
  options: {
    style?: string;
    align?: 'left' | 'center' | 'right';
    before?: number;
    after?: number;
    keepNext?: boolean;
    pageBreakBefore?: boolean;
  } = {},
): string {
  const pPr = [
    options.style ? `<w:pStyle w:val="${options.style}"/>` : '',
    options.align ? `<w:jc w:val="${options.align}"/>` : '',
    options.before != null || options.after != null
      ? `<w:spacing${options.before != null ? ` w:before="${options.before}"` : ''}${options.after != null ? ` w:after="${options.after}"` : ''}/>`
      : '',
    options.keepNext ? '<w:keepNext/>' : '',
    options.pageBreakBefore ? '<w:pageBreakBefore/>' : '',
  ].join('');
  const body = typeof content === 'string'
    ? run(content)
    : content.map(item => run(item.text, item)).join('');
  return `<w:p>${pPr ? `<w:pPr>${pPr}</w:pPr>` : ''}${body || '<w:r><w:t/></w:r>'}</w:p>`;
}

function cellXml(cell: DocxCell, width: number, defaultFill?: string): string {
  const fill = cell.fill ?? defaultFill;
  const content = cell.paragraphs
    ? cell.paragraphs.join('')
    : paragraph(
      cell.runs ?? [{ text: String(cell.text ?? ''), bold: cell.bold, color: cell.color }],
      { style: 'TableText', align: cell.align ?? 'left', after: 0 },
    );
  return `<w:tc><w:tcPr><w:tcW w:w="${width}" w:type="dxa"/>${fill ? `<w:shd w:val="clear" w:fill="${fill}"/>` : ''}<w:vAlign w:val="center"/></w:tcPr>${content}</w:tc>`;
}

function tableXml(
  headers: DocxCell[],
  rows: DocxCell[][],
  widths: number[],
  options: { noBorders?: boolean; headerFill?: string; zebra?: boolean; noData?: string } = {},
): string {
  const borders = options.noBorders
    ? '<w:tblBorders><w:top w:val="nil"/><w:left w:val="nil"/><w:bottom w:val="nil"/><w:right w:val="nil"/><w:insideH w:val="nil"/><w:insideV w:val="nil"/></w:tblBorders>'
    : `<w:tblBorders><w:top w:val="single" w:sz="4" w:color="${BORDER}"/><w:left w:val="single" w:sz="4" w:color="${BORDER}"/><w:bottom w:val="single" w:sz="4" w:color="${BORDER}"/><w:right w:val="single" w:sz="4" w:color="${BORDER}"/><w:insideH w:val="single" w:sz="4" w:color="${BORDER}"/><w:insideV w:val="single" w:sz="4" w:color="${BORDER}"/></w:tblBorders>`;
  const props = `<w:tblPr><w:tblW w:w="${widths.reduce((sum, width) => sum + width, 0)}" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblInd w:w="120" w:type="dxa"/>${borders}<w:tblCellMar><w:top w:w="100" w:type="dxa"/><w:left w:w="120" w:type="dxa"/><w:bottom w:w="100" w:type="dxa"/><w:right w:w="120" w:type="dxa"/></w:tblCellMar></w:tblPr>`;
  const grid = `<w:tblGrid>${widths.map(width => `<w:gridCol w:w="${width}"/>`).join('')}</w:tblGrid>`;
  const header = headers.length
    ? `<w:tr><w:trPr><w:tblHeader/><w:cantSplit/></w:trPr>${headers.map((cell, index) => cellXml({ ...cell, bold: true, color: 'FFFFFF', fill: cell.fill ?? options.headerFill ?? BRAND }, widths[index])).join('')}</w:tr>`
    : '';
  const dataRows = rows.length ? rows : [[{ text: options.noData ?? '' }]];
  const body = dataRows.map((row, rowIndex) => {
    const complete = widths.map((_, index) => row[index] ?? { text: '' });
    const fill = options.zebra && rowIndex % 2 === 1 ? ALT : undefined;
    return `<w:tr><w:trPr><w:cantSplit/></w:trPr>${complete.map((cell, index) => cellXml(cell, widths[index], fill)).join('')}</w:tr>`;
  }).join('');
  return `<w:tbl>${props}${grid}${header}${body}</w:tbl>`;
}

function statusCell(product: InventoryWorkbookProduct, language: InventoryDocumentLanguage): DocxCell {
  const copy = inventoryDocumentCopy(language);
  if (finite(product.currentStock) <= 0) return { text: copy.status.out, fill: DANGER_FILL, color: 'B42318', bold: true, align: 'center' };
  if (finite(product.minStock) > 0 && finite(product.currentStock) <= finite(product.minStock)) {
    return { text: copy.status.low, fill: WARNING_FILL, color: '9A5B00', bold: true, align: 'center' };
  }
  return { text: copy.status.available, fill: SUCCESS_FILL, color: '087A61', bold: true, align: 'center' };
}

function consumptionBy(
  movements: InventoryWorkbookMovement[],
  key: (movement: InventoryWorkbookMovement) => string,
  fallback: string,
): Array<[string, number]> {
  const totals = new Map<string, number>();
  for (const movement of movements) {
    if (movement.movementType !== 'out') continue;
    const label = key(movement).trim() || fallback;
    totals.set(label, (totals.get(label) ?? 0) + finite(movement.quantity));
  }
  return [...totals.entries()].sort((a, b) => b[1] - a[1]);
}

function documentXml(
  products: InventoryWorkbookProduct[],
  movements: InventoryWorkbookMovement[],
  chantierName: string,
  generatedAt: Date,
  language: InventoryDocumentLanguage,
): string {
  const copy = inventoryDocumentCopy(language);
  const docx = DOCX_COPY[language];
  const sortedProducts = [...products].sort((a, b) => a.reference.localeCompare(b.reference, copy.locale));
  const reorder = sortedProducts.filter(product => finite(product.minStock) > 0 && finite(product.currentStock) <= finite(product.minStock));
  const totalUnits = sortedProducts.reduce((sum, product) => sum + finite(product.currentStock), 0);
  const totalEntries = movements.filter(movement => movement.movementType === 'in').reduce((sum, movement) => sum + finite(movement.quantity), 0);
  const totalExits = movements.filter(movement => movement.movementType === 'out').reduce((sum, movement) => sum + finite(movement.quantity), 0);
  const buildings = consumptionBy(movements, movement => movement.buildingName || movement.zoneName || '', copy.notProvided);
  const companies = consumptionBy(movements, movement => movement.companyName || '', copy.notProvided);
  const latest = [...movements]
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, 50);
  const generatedLabel = formatDate(generatedAt, copy.locale);

  const metadata = tableXml([], [[
    { runs: [{ text: `${copy.workbook.siteLabel}: `, bold: true, color: BRAND }, { text: chantierName, color: TEXT }] },
    { runs: [{ text: `${copy.pdf.generatedOn}: `, bold: true, color: BRAND }, { text: generatedLabel, color: TEXT }], align: 'right' },
  ]], [7_080, 7_080], { noBorders: true });

  const kpiValues = [sortedProducts.length, totalUnits, totalEntries, totalExits, reorder.length];
  const kpiLabels = [copy.pdf.kpiReferences, copy.pdf.kpiUnits, copy.pdf.kpiEntries, copy.pdf.kpiExits, copy.pdf.kpiReorder];
  const kpis = tableXml([], [kpiValues.map((value, index) => ({
    fill: index === 4 && reorder.length ? WARNING_FILL : BRAND_LIGHT,
    align: 'center',
    paragraphs: [
      paragraph([{ text: formatNumber(value, copy.locale), bold: true, color: index === 4 && reorder.length ? '9A5B00' : BRAND, size: 34 }], { align: 'center', after: 40 }),
      paragraph([{ text: kpiLabels[index], bold: true, color: MUTED, size: 15 }], { align: 'center', after: 0 }),
    ],
  }))], [2_832, 2_832, 2_832, 2_832, 2_832], { noBorders: false });

  const stockRows = sortedProducts.map(product => [
    { text: product.reference, bold: true, color: BRAND },
    { text: product.designation },
    statusCell(product, language),
    { text: formatNumber(product.currentStock, copy.locale), align: 'right', bold: true },
    { text: formatNumber(product.minStock, copy.locale), align: 'right' },
    { text: formatNumber(product.totalEntries, copy.locale), align: 'right' },
    { text: formatNumber(product.totalExits, copy.locale), align: 'right' },
    { text: product.location || copy.notProvided },
  ] satisfies DocxCell[]);

  const reorderRows = reorder.map(product => [
    { text: product.reference, bold: true, color: BRAND },
    { text: product.designation },
    statusCell(product, language),
    { text: formatNumber(product.currentStock, copy.locale), align: 'right' },
    { text: formatNumber(product.minStock, copy.locale), align: 'right' },
    { text: formatNumber(Math.max(0, finite(product.minStock) - finite(product.currentStock)), copy.locale), align: 'right', bold: true, color: '9A5B00' },
    { text: product.supplier || copy.notProvided },
  ] satisfies DocxCell[]);

  const movementRows = latest.map(movement => [
    { text: formatDate(movement.createdAt, copy.locale) },
    { text: movement.movementType === 'in' ? copy.movement.in : copy.movement.out, align: 'center', bold: true, color: movement.movementType === 'in' ? '087A61' : 'B42318' },
    { text: movement.reference, bold: true, color: BRAND },
    { text: movement.designation },
    { text: formatNumber(movement.quantity, copy.locale), align: 'right', bold: true },
    { text: movement.buildingName || movement.zoneName || copy.notProvided },
    { text: movement.companyName || movement.supplier || copy.notProvided },
  ] satisfies DocxCell[]);

  const consumptionTable = (rows: Array<[string, number]>, headers: string[]) => tableXml(
    headers.map(text => ({ text })),
    rows.map(([label, quantity]) => [{ text: label }, { text: formatNumber(quantity, copy.locale), align: 'right', bold: true }]),
    [10_400, 3_760],
    { zebra: true, noData: copy.noData },
  );

  const body = [
    paragraph([{ text: 'BUILDTRACK', bold: true, color: BRAND, size: 17 }], { after: 50 }),
    paragraph(docx.reportTitle, { style: 'Title', after: 60, keepNext: true }),
    paragraph([{ text: copy.pdf.tagline, color: MUTED, size: 22 }], { after: 180 }),
    metadata,
    paragraph(docx.executiveSummary, { style: 'Heading1', before: 220, after: 100, keepNext: true }),
    kpis,
    reorder.length
      ? tableXml([], [[{ text: copy.pdf.lowStock(reorder.length), fill: WARNING_FILL, color: '7A5A00', bold: true }]], [CONTENT_WIDTH], { noBorders: false })
      : tableXml([], [[{ text: copy.workbook.noBelowMinimum, fill: SUCCESS_FILL, color: '087A61', bold: true }]], [CONTENT_WIDTH], { noBorders: false }),
    paragraph(copy.pdf.stockSection, { style: 'Heading1', before: 260, after: 100, keepNext: true }),
    tableXml(
      [
        copy.pdf.stockHeaders[0],
        copy.pdf.stockHeaders[1],
        copy.workbook.headers.stock[2],
        copy.pdf.stockHeaders[2],
        copy.pdf.stockHeaders[3],
        copy.pdf.stockHeaders[4],
        copy.pdf.stockHeaders[5],
        copy.pdf.stockHeaders[6],
      ].map(text => ({ text })),
      stockRows,
      [1_650, 3_350, 1_450, 1_050, 1_050, 1_050, 1_050, 3_510],
      { zebra: true, noData: copy.noData },
    ),
    paragraph(copy.pdf.reorderSection, { style: 'Heading1', before: 260, after: 100, keepNext: true }),
    tableXml(
      [copy.workbook.headers.reorder[0], copy.workbook.headers.reorder[1], copy.workbook.headers.reorder[2], copy.workbook.headers.reorder[3], copy.workbook.headers.reorder[4], copy.workbook.headers.reorder[5], copy.workbook.headers.reorder[7]].map(text => ({ text })),
      reorderRows,
      [1_650, 3_100, 1_500, 1_050, 1_050, 1_350, 4_460],
      { zebra: true, noData: copy.workbook.noBelowMinimum },
    ),
    paragraph(copy.pdf.buildingSection, { style: 'Heading1', before: 260, after: 100, keepNext: true }),
    consumptionTable(buildings, copy.pdf.buildingHeaders),
    paragraph(copy.pdf.companySection, { style: 'Heading1', before: 260, after: 100, keepNext: true }),
    consumptionTable(companies, copy.pdf.companyHeaders),
    paragraph(docx.latestMovements, { style: 'Heading1', before: 260, after: 80, keepNext: true, pageBreakBefore: true }),
    paragraph([{ text: docx.latestMovementsNote(latest.length, movements.length), color: MUTED, italic: true }], { after: 100 }),
    tableXml(
      copy.pdf.movementHeaders.map(text => ({ text })),
      movementRows,
      [2_000, 1_200, 1_550, 2_750, 1_000, 2_800, 2_860],
      { zebra: true, noData: copy.noData },
    ),
    paragraph([{ text: `${docx.generatedBy} - ${docx.confidential}`, color: MUTED, size: 17 }], { align: 'right', before: 180, after: 0 }),
  ].join('');

  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:body>${body}<w:sectPr><w:headerReference w:type="default" r:id="rId3"/><w:footerReference w:type="default" r:id="rId4"/><w:pgSz w:w="15840" w:h="12240" w:orient="landscape"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720" w:header="360" w:footer="360" w:gutter="0"/><w:cols w:space="720"/><w:docGrid w:linePitch="360"/></w:sectPr></w:body></w:document>`;
}

function stylesXml(): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:color w:val="${TEXT}"/><w:sz w:val="21"/><w:szCs w:val="21"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="120" w:line="264" w:lineRule="auto"/></w:pPr></w:pPrDefault></w:docDefaults>
  <w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:qFormat/><w:pPr><w:spacing w:after="120" w:line="264" w:lineRule="auto"/></w:pPr><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="21"/><w:szCs w:val="21"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/><w:qFormat/><w:pPr><w:spacing w:before="0" w:after="60"/><w:keepNext/></w:pPr><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:b/><w:color w:val="${TEXT}"/><w:sz w:val="44"/><w:szCs w:val="44"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/><w:qFormat/><w:uiPriority w:val="9"/><w:pPr><w:keepNext/><w:keepLines/><w:spacing w:before="240" w:after="120"/><w:outlineLvl w:val="0"/></w:pPr><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:b/><w:color w:val="${BRAND}"/><w:sz w:val="28"/><w:szCs w:val="28"/></w:rPr></w:style>
  <w:style w:type="paragraph" w:styleId="TableText"><w:name w:val="Table Text"/><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:before="0" w:after="0" w:line="220" w:lineRule="auto"/></w:pPr><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:style>
</w:styles>`;
}

function headerXml(chantierName: string, language: InventoryDocumentLanguage): string {
  const docx = DOCX_COPY[language];
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:hdr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:tbl><w:tblPr><w:tblW w:w="${CONTENT_WIDTH}" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblBorders><w:bottom w:val="single" w:sz="8" w:color="${BRAND}"/><w:top w:val="nil"/><w:left w:val="nil"/><w:right w:val="nil"/><w:insideH w:val="nil"/><w:insideV w:val="nil"/></w:tblBorders></w:tblPr><w:tblGrid><w:gridCol w:w="7080"/><w:gridCol w:w="7080"/></w:tblGrid><w:tr>${cellXml({ runs: [{ text: 'BuildTrack', bold: true, color: BRAND, size: 20 }] }, 7_080)}${cellXml({ runs: [{ text: `${docx.reportTitle} - ${chantierName}`, color: MUTED, size: 16 }], align: 'right' }, 7_080)}</w:tr></w:tbl></w:hdr>`;
}

function footerXml(language: InventoryDocumentLanguage): string {
  const copy = DOCX_COPY[language];
  const pageField = `<w:p><w:pPr><w:jc w:val="right"/><w:spacing w:after="0"/></w:pPr>${run(`${copy.page} `, { color: MUTED, size: 16 })}<w:fldSimple w:instr=" PAGE ">${run('1', { color: MUTED, size: 16 })}</w:fldSimple>${run(` ${copy.of} `, { color: MUTED, size: 16 })}<w:fldSimple w:instr=" NUMPAGES ">${run('1', { color: MUTED, size: 16 })}</w:fldSimple></w:p>`;
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:tbl><w:tblPr><w:tblW w:w="${CONTENT_WIDTH}" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblBorders><w:top w:val="single" w:sz="4" w:color="${BORDER}"/><w:left w:val="nil"/><w:bottom w:val="nil"/><w:right w:val="nil"/><w:insideH w:val="nil"/><w:insideV w:val="nil"/></w:tblBorders></w:tblPr><w:tblGrid><w:gridCol w:w="7080"/><w:gridCol w:w="7080"/></w:tblGrid><w:tr>${cellXml({ runs: [{ text: copy.confidential, color: MUTED, size: 16 }] }, 7_080)}${cellXml({ paragraphs: [pageField] }, 7_080)}</w:tr></w:tbl></w:ftr>`;
}

export function buildInventoryDocxBytes(
  zipRuntime: InventoryDocxZipRuntime,
  products: InventoryWorkbookProduct[],
  movements: InventoryWorkbookMovement[],
  chantierName: string,
  generatedAt = new Date(),
  language: InventoryDocumentLanguage = 'fr',
): Uint8Array {
  const { strToU8, zipSync } = zipRuntime;
  const copy = inventoryDocumentCopy(language);
  const isoDate = generatedAt.toISOString();
  const files: Record<string, Uint8Array> = {
    '[Content_Types].xml': strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/settings.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"/><Override PartName="/word/header1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/></Types>`),
    '_rels/.rels': strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>`),
    'word/document.xml': strToU8(documentXml(products, movements, chantierName, generatedAt, language)),
    'word/styles.xml': strToU8(stylesXml()),
    'word/settings.xml': strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:settings xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:zoom w:percent="100"/><w:defaultTabStop w:val="720"/><w:updateFields w:val="true"/><w:compat><w:compatSetting w:name="compatibilityMode" w:uri="http://schemas.microsoft.com/office/word" w:val="15"/></w:compat></w:settings>`),
    'word/header1.xml': strToU8(headerXml(chantierName, language)),
    'word/footer1.xml': strToU8(footerXml(language)),
    'word/_rels/document.xml.rels': strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/header" Target="header1.xml"/><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/></Relationships>`),
    'docProps/core.xml': strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>${xml(DOCX_COPY[language].reportTitle)}</dc:title><dc:subject>${xml(copy.workbook.subject)}</dc:subject><dc:creator>BuildTrack</dc:creator><cp:lastModifiedBy>BuildTrack</cp:lastModifiedBy><dcterms:created xsi:type="dcterms:W3CDTF">${isoDate}</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">${isoDate}</dcterms:modified></cp:coreProperties>`),
    'docProps/app.xml': strToU8(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Application>BuildTrack</Application><AppVersion>1.0</AppVersion><Company>BuildTrack</Company></Properties>`),
  };
  return zipSync(files, { level: 6 });
}

export function inventoryDocxBytesToBase64(bytes: Uint8Array): string {
  return inventoryWorkbookBytesToBase64(bytes);
}
