import { useTranslation } from 'react-i18next';

const fr = {
  module: 'Stock chantier', subtitle: 'Matériel et mouvements', entry: 'ENTRÉE', exit: 'SORTIE', stock: 'STOCK', history: 'HISTORIQUE',
  searchReference: 'Rechercher une référence ou un code-barres', lowStock: 'Stock faible', orderRequired: 'Commande nécessaire',
  references: 'Références', units: 'Unités en stock', recentMovements: 'Derniers mouvements', seeAll: 'Voir tout', noMovement: 'Aucun mouvement enregistré',
  noProduct: 'Aucun produit trouvé', noSite: 'Sélectionnez un chantier pour gérer son stock.', chooseSite: 'Choisir un chantier', restricted: 'Vous n’avez pas accès au stock chantier.',
  scanEntry: 'Scanner une entrée', scanExit: 'Scanner une sortie', scanHint: 'Placez le code-barres ou QR code dans le cadre', cameraPermission: 'La caméra est nécessaire pour scanner les étiquettes.',
  allowCamera: 'Autoriser la caméra', manualEntry: 'Saisir manuellement', takeLabelPhoto: 'Photographier l’étiquette', ocrReading: 'Lecture locale de la référence…', rescan: 'Scanner à nouveau', torch: 'Lampe',
  newEntry: 'Nouvelle entrée', newExit: 'Nouvelle sortie', product: 'Produit', reference: 'Référence', designation: 'Désignation', barcode: 'Code-barres / QR',
  quantity: 'Quantité', supplier: 'Fournisseur', location: 'Emplacement', destination: 'Bâtiment / destination', zone: 'Zone', company: 'Entreprise', person: 'Personne', comment: 'Commentaire',
  minimumStock: 'Stock minimum', optional: 'Facultatif', currentStock: 'Stock actuel', afterMovement: 'Après mouvement', validateEntry: 'VALIDER L’ENTRÉE', validateExit: 'VALIDER LA SORTIE',
  knownProduct: 'Produit trouvé', newProduct: 'Nouvelle référence', insufficient: 'Stock insuffisant', negativeWarning: 'Cette sortie dépasse le stock disponible.', allowNegative: 'Autoriser exceptionnellement le stock négatif',
  destinationRequired: 'Sélectionnez une destination.', referenceRequired: 'Saisissez une référence.', designationRequired: 'Saisissez une désignation pour la nouvelle référence.', quantityRequired: 'Saisissez une quantité supérieure à zéro.',
  movementSaved: 'Mouvement enregistré', queued: 'Enregistré hors ligne — synchronisation automatique à la reconnexion.', synchronized: 'Le stock a été mis à jour.',
  filterAll: 'Tous', filterEntries: 'Entrées', filterExits: 'Sorties', onlyLow: 'Stock faible uniquement', export: 'Exporter', refresh: 'Actualiser',
  productSheet: 'Fiche produit', edit: 'Modifier', save: 'Enregistrer', entries: 'Entrées', exits: 'Sorties', available: 'Disponible', movementHistory: 'Historique des mouvements',
  photo: 'Photo', changePhoto: 'Changer la photo', addPhoto: 'Ajouter une photo', exportPdf: 'Rapport PDF complet', exportStockCsv: 'État du stock (Excel .xlsx)', exportEntriesCsv: 'Entrées (Excel .xlsx)',
  exportExitsCsv: 'Sorties (Excel .xlsx)', exportBuildingCsv: 'Consommation par bâtiment (Excel)', exportCompanyCsv: 'Consommation par entreprise (Excel)', exportReorderCsv: 'Produits à commander (Excel)', exportReady: 'Export prêt',
  pending: 'En attente de synchronisation', other: 'Autre', confirmNegativeTitle: 'Confirmer le stock négatif', confirmNegative: 'Le stock passera à {{stock}}. Voulez-vous continuer ?', confirm: 'Confirmer',
  editProduct: 'Modifier la fiche produit', error: 'Erreur', cancel: 'Annuler', close: 'Fermer', select: 'Sélectionner', noHistory: 'Aucun historique pour ce produit.',
};

const en: typeof fr = {
  module: 'Site inventory', subtitle: 'Materials and movements', entry: 'RECEIVE', exit: 'ISSUE', stock: 'STOCK', history: 'HISTORY',
  searchReference: 'Search a reference or barcode', lowStock: 'Low stock', orderRequired: 'Order required', references: 'References', units: 'Units in stock', recentMovements: 'Recent movements', seeAll: 'See all', noMovement: 'No movement recorded',
  noProduct: 'No product found', noSite: 'Select a site to manage its inventory.', chooseSite: 'Choose a site', restricted: 'You do not have access to site inventory.',
  scanEntry: 'Scan receipt', scanExit: 'Scan issue', scanHint: 'Place the barcode or QR code inside the frame', cameraPermission: 'Camera access is required to scan labels.', allowCamera: 'Allow camera', manualEntry: 'Enter manually', takeLabelPhoto: 'Photograph label', ocrReading: 'Reading the reference on device…', rescan: 'Scan again', torch: 'Torch',
  newEntry: 'New receipt', newExit: 'New issue', product: 'Product', reference: 'Reference', designation: 'Description', barcode: 'Barcode / QR', quantity: 'Quantity', supplier: 'Supplier', location: 'Location', destination: 'Building / destination', zone: 'Zone', company: 'Company', person: 'Person', comment: 'Comment', minimumStock: 'Minimum stock', optional: 'Optional', currentStock: 'Current stock', afterMovement: 'After movement', validateEntry: 'CONFIRM RECEIPT', validateExit: 'CONFIRM ISSUE',
  knownProduct: 'Product found', newProduct: 'New reference', insufficient: 'Insufficient stock', negativeWarning: 'This issue exceeds available stock.', allowNegative: 'Exceptionally allow negative stock', destinationRequired: 'Select a destination.', referenceRequired: 'Enter a reference.', designationRequired: 'Enter a description for the new reference.', quantityRequired: 'Enter a quantity greater than zero.', movementSaved: 'Movement recorded', queued: 'Saved offline — automatic sync when reconnected.', synchronized: 'Inventory has been updated.',
  filterAll: 'All', filterEntries: 'Receipts', filterExits: 'Issues', onlyLow: 'Low stock only', export: 'Export', refresh: 'Refresh', productSheet: 'Product sheet', edit: 'Edit', save: 'Save', entries: 'Receipts', exits: 'Issues', available: 'Available', movementHistory: 'Movement history', photo: 'Photo', changePhoto: 'Change photo', addPhoto: 'Add photo', exportPdf: 'Complete PDF report', exportStockCsv: 'Stock status (Excel .xlsx)', exportEntriesCsv: 'Receipts (Excel .xlsx)', exportExitsCsv: 'Issues (Excel .xlsx)', exportBuildingCsv: 'Consumption by building (Excel)', exportCompanyCsv: 'Consumption by company (Excel)', exportReorderCsv: 'Products to order (Excel)', exportReady: 'Export ready', pending: 'Pending synchronization', other: 'Other', confirmNegativeTitle: 'Confirm negative stock', confirmNegative: 'Stock will become {{stock}}. Continue?', confirm: 'Confirm', editProduct: 'Edit product sheet', error: 'Error', cancel: 'Cancel', close: 'Close', select: 'Select', noHistory: 'No history for this product.',
};

const es: typeof fr = {
  module: 'Stock de obra', subtitle: 'Materiales y movimientos', entry: 'ENTRADA', exit: 'SALIDA', stock: 'STOCK', history: 'HISTORIAL',
  searchReference: 'Buscar referencia o código de barras', lowStock: 'Stock bajo', orderRequired: 'Pedido necesario', references: 'Referencias', units: 'Unidades en stock', recentMovements: 'Últimos movimientos', seeAll: 'Ver todo', noMovement: 'Ningún movimiento registrado', noProduct: 'Ningún producto encontrado', noSite: 'Selecciona una obra para gestionar su stock.', chooseSite: 'Elegir obra', restricted: 'No tienes acceso al stock de obra.',
  scanEntry: 'Escanear entrada', scanExit: 'Escanear salida', scanHint: 'Coloca el código de barras o QR dentro del marco', cameraPermission: 'Se necesita la cámara para escanear etiquetas.', allowCamera: 'Autorizar cámara', manualEntry: 'Introducir manualmente', takeLabelPhoto: 'Fotografiar etiqueta', ocrReading: 'Leyendo la referencia en el dispositivo…', rescan: 'Escanear de nuevo', torch: 'Linterna', newEntry: 'Nueva entrada', newExit: 'Nueva salida', product: 'Producto', reference: 'Referencia', designation: 'Descripción', barcode: 'Código de barras / QR', quantity: 'Cantidad', supplier: 'Proveedor', location: 'Ubicación', destination: 'Edificio / destino', zone: 'Zona', company: 'Empresa', person: 'Persona', comment: 'Comentario', minimumStock: 'Stock mínimo', optional: 'Opcional', currentStock: 'Stock actual', afterMovement: 'Después del movimiento', validateEntry: 'VALIDAR ENTRADA', validateExit: 'VALIDAR SALIDA',
  knownProduct: 'Producto encontrado', newProduct: 'Nueva referencia', insufficient: 'Stock insuficiente', negativeWarning: 'Esta salida supera el stock disponible.', allowNegative: 'Autorizar excepcionalmente stock negativo', destinationRequired: 'Selecciona un destino.', referenceRequired: 'Introduce una referencia.', designationRequired: 'Introduce una descripción para la nueva referencia.', quantityRequired: 'Introduce una cantidad superior a cero.', movementSaved: 'Movimiento registrado', queued: 'Guardado sin conexión — sincronización automática al reconectar.', synchronized: 'El stock se ha actualizado.', filterAll: 'Todos', filterEntries: 'Entradas', filterExits: 'Salidas', onlyLow: 'Solo stock bajo', export: 'Exportar', refresh: 'Actualizar', productSheet: 'Ficha de producto', edit: 'Editar', save: 'Guardar', entries: 'Entradas', exits: 'Salidas', available: 'Disponible', movementHistory: 'Historial de movimientos', photo: 'Foto', changePhoto: 'Cambiar foto', addPhoto: 'Añadir foto', exportPdf: 'Informe PDF completo', exportStockCsv: 'Estado del stock (Excel .xlsx)', exportEntriesCsv: 'Entradas (Excel .xlsx)', exportExitsCsv: 'Salidas (Excel .xlsx)', exportBuildingCsv: 'Consumo por edificio (Excel)', exportCompanyCsv: 'Consumo por empresa (Excel)', exportReorderCsv: 'Productos a pedir (Excel)', exportReady: 'Exportación lista', pending: 'Pendiente de sincronización', other: 'Otro', confirmNegativeTitle: 'Confirmar stock negativo', confirmNegative: 'El stock pasará a {{stock}}. ¿Continuar?', confirm: 'Confirmar', editProduct: 'Editar ficha de producto', error: 'Error', cancel: 'Cancelar', close: 'Cerrar', select: 'Seleccionar', noHistory: 'No hay historial para este producto.',
};

export type InventoryCopy = typeof fr;

export function useInventoryCopy(): InventoryCopy {
  const { i18n } = useTranslation();
  const language = (i18n.resolvedLanguage ?? i18n.language ?? 'fr').split('-')[0];
  return language === 'en' ? en : language === 'es' ? es : fr;
}
