import { Reserve, Company, Task, Document, Photo, Message } from '@/constants/types';

export const MOCK_RESERVES: Reserve[] = [
  {
    id: 'RSV-001',
    title: 'Fissure mur porteur Niveau 2',
    description: 'Fissure diagonale de 3mm visible sur le mur porteur sud du bâtiment A. Nécessite expertise structure urgente.',
    building: 'A',
    zone: 'Zone Sud',
    level: 'R+2',
    company: 'EIFFAGE Gros Œuvre',
    priority: 'critical',
    status: 'open',
    createdAt: '2026-03-01',
    deadline: '15/04/2026',
    planX: 18,
    planY: 28,
    comments: [
      { id: 'c1', author: 'J. Dupont', content: 'Expert contacté, RDV lundi matin.', createdAt: '2026-03-02' },
    ],
    history: [
      { id: 'h1', action: 'Réserve créée', author: 'J. Dupont', createdAt: '2026-03-01' },
    ],
  },
  {
    id: 'RSV-002',
    title: 'Défaut étanchéité toiture Bât B',
    description: "Infiltration d'eau détectée au niveau de la jonction toiture/acrotère côté nord. Zone de 2m² concernée.",
    building: 'B',
    zone: 'Zone Nord',
    level: 'R+3',
    company: 'BOUYGUES Construction',
    priority: 'high',
    status: 'in_progress',
    createdAt: '2026-03-10',
    deadline: '30/04/2026',
    planX: 32,
    planY: 14,
    comments: [
      { id: 'c2', author: 'M. Martin', content: 'Travaux de reprise planifiés semaine prochaine.', createdAt: '2026-03-12' },
    ],
    history: [
      { id: 'h2', action: 'Réserve créée', author: 'M. Martin', createdAt: '2026-03-10' },
      { id: 'h3', action: 'Statut modifié', author: 'M. Martin', oldValue: 'Ouvert', newValue: 'En cours', createdAt: '2026-03-15' },
    ],
  },
  {
    id: 'RSV-003',
    title: 'Installation électrique non conforme',
    description: 'Câblage électrique non conforme aux normes NFC 15-100 dans le local technique RDC. Absence de protection différentielle.',
    building: 'A',
    zone: 'Zone Est',
    level: 'RDC',
    company: 'VINCI Électricité',
    priority: 'high',
    status: 'verification',
    createdAt: '2026-02-20',
    deadline: '20/03/2026',
    planX: 68,
    planY: 72,
    comments: [
      { id: 'c3', author: 'P. Bernard', content: 'Reprise effectuée, en attente de contrôle CONSUEL.', createdAt: '2026-03-18' },
    ],
    history: [
      { id: 'h4', action: 'Réserve créée', author: 'P. Bernard', createdAt: '2026-02-20' },
      { id: 'h5', action: 'Statut modifié', author: 'P. Bernard', oldValue: 'En cours', newValue: 'Vérification', createdAt: '2026-03-18' },
    ],
  },
  {
    id: 'RSV-004',
    title: 'Revêtement sol dégradé Hall C',
    description: "Carrelage fissuré et décollé sur environ 8m² dans le hall principal du bâtiment C. Risque de chute.",
    building: 'C',
    zone: 'Zone Centre',
    level: 'RDC',
    company: 'GECINA Finitions',
    priority: 'medium',
    status: 'waiting',
    createdAt: '2026-03-05',
    deadline: '10/05/2026',
    planX: 26,
    planY: 58,
    comments: [],
    history: [
      { id: 'h6', action: 'Réserve créée', author: 'S. Leroy', createdAt: '2026-03-05' },
      { id: 'h7', action: 'Statut modifié', author: 'S. Leroy', oldValue: 'Ouvert', newValue: 'En attente livraison carrelage', createdAt: '2026-03-08' },
    ],
  },
  {
    id: 'RSV-005',
    title: 'Joints façade manquants Bât B',
    description: "Joints de dilatation absents sur la façade ouest, sur une longueur de 12 mètres au niveau R+1.",
    building: 'B',
    zone: 'Zone Ouest',
    level: 'R+1',
    company: 'BOUYGUES Construction',
    priority: 'medium',
    status: 'open',
    createdAt: '2026-03-15',
    deadline: '15/05/2026',
    planX: 58,
    planY: 62,
    comments: [],
    history: [
      { id: 'h8', action: 'Réserve créée', author: 'J. Dupont', createdAt: '2026-03-15' },
    ],
  },
  {
    id: 'RSV-006',
    title: 'Câblage réseau informatique incomplet',
    description: "Câblage réseau non terminé dans les bureaux 201 à 208. 24 prises RJ45 manquantes.",
    building: 'A',
    zone: 'Zone Nord',
    level: 'R+2',
    company: 'VINCI Électricité',
    priority: 'low',
    status: 'in_progress',
    createdAt: '2026-03-12',
    deadline: '20/04/2026',
    planX: 42,
    planY: 45,
    comments: [
      { id: 'c4', author: 'P. Bernard', content: '12 prises posées ce jour, reste 12.', createdAt: '2026-03-22' },
    ],
    history: [
      { id: 'h9', action: 'Réserve créée', author: 'P. Bernard', createdAt: '2026-03-12' },
      { id: 'h10', action: 'Statut modifié', author: 'P. Bernard', oldValue: 'Ouvert', newValue: 'En cours', createdAt: '2026-03-18' },
    ],
  },
  {
    id: 'RSV-007',
    title: 'Porte coupe-feu CF60 non installée',
    description: "Porte coupe-feu CF60 manquante au niveau cage escalier bâtiment C. Non-conformité réglementaire ERP.",
    building: 'C',
    zone: 'Zone Est',
    level: 'R+1',
    company: 'GECINA Finitions',
    priority: 'critical',
    status: 'open',
    createdAt: '2026-03-20',
    deadline: '10/04/2026',
    planX: 62,
    planY: 32,
    comments: [],
    history: [
      { id: 'h11', action: 'Réserve créée', author: 'S. Leroy', createdAt: '2026-03-20' },
    ],
  },
  {
    id: 'RSV-008',
    title: 'Peinture façade sud non terminée',
    description: "Peinture façade côté sud bâtiment B non terminée. Il manque environ 30% de la surface totale.",
    building: 'B',
    zone: 'Zone Sud',
    level: 'R+2',
    company: 'BOUYGUES Construction',
    priority: 'low',
    status: 'closed',
    createdAt: '2026-01-15',
    deadline: '10/02/2026',
    planX: 72,
    planY: 80,
    comments: [
      { id: 'c5', author: 'M. Martin', content: 'Travaux terminés et validés.', createdAt: '2026-02-10' },
    ],
    history: [
      { id: 'h12', action: 'Réserve créée', author: 'M. Martin', createdAt: '2026-01-15' },
      { id: 'h13', action: 'Statut modifié', author: 'M. Martin', oldValue: 'En cours', newValue: 'Clôturé', createdAt: '2026-02-10' },
    ],
  },
  {
    id: 'RSV-009',
    title: 'Escalier de secours Bât A incomplet',
    description: "Main courante escalier de secours côté nord non fixée. Garde-corps à hauteur insuffisante (85cm au lieu de 100cm).",
    building: 'A',
    zone: 'Zone Nord',
    level: 'R+3',
    company: 'EIFFAGE Gros Œuvre',
    priority: 'high',
    status: 'open',
    createdAt: '2026-03-18',
    deadline: '01/05/2026',
    planX: 82,
    planY: 22,
    comments: [],
    history: [
      { id: 'h14', action: 'Réserve créée', author: 'J. Dupont', createdAt: '2026-03-18' },
    ],
  },
  {
    id: 'RSV-010',
    title: 'Robinetterie non conforme Bât C',
    description: "Mitigeurs thermostatiques non installés dans les sanitaires du niveau 2. Normes EHPAD non respectées.",
    building: 'C',
    zone: 'Zone Ouest',
    level: 'R+2',
    company: 'GECINA Finitions',
    priority: 'medium',
    status: 'verification',
    createdAt: '2026-02-28',
    deadline: '28/03/2026',
    planX: 46,
    planY: 76,
    comments: [
      { id: 'c6', author: 'S. Leroy', content: 'Pose effectuée, vérification en cours.', createdAt: '2026-03-25' },
    ],
    history: [
      { id: 'h15', action: 'Réserve créée', author: 'S. Leroy', createdAt: '2026-02-28' },
      { id: 'h16', action: 'Statut modifié', author: 'S. Leroy', oldValue: 'En cours', newValue: 'Vérification', createdAt: '2026-03-25' },
    ],
  },
];

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'co1',
    name: 'BOUYGUES Construction',
    shortName: 'BOUYGUES',
    color: '#10B981',
    plannedWorkers: 28,
    actualWorkers: 25,
    hoursWorked: 210,
    zone: 'Bâtiment A & B',
    contact: 'Marc Martin — 06 23 45 67 89',
  },
  {
    id: 'co2',
    name: 'EIFFAGE Gros Œuvre',
    shortName: 'EIFFAGE',
    color: '#F59E0B',
    plannedWorkers: 18,
    actualWorkers: 16,
    hoursWorked: 144,
    zone: 'Bâtiment A',
    contact: 'Jean Dupont — 06 12 34 56 78',
  },
  {
    id: 'co3',
    name: 'VINCI Électricité',
    shortName: 'VINCI',
    color: '#3B82F6',
    plannedWorkers: 12,
    actualWorkers: 10,
    hoursWorked: 96,
    zone: 'Bâtiments A & B',
    contact: 'Paul Bernard — 06 34 56 78 90',
  },
  {
    id: 'co4',
    name: 'GECINA Finitions',
    shortName: 'GECINA',
    color: '#EC4899',
    plannedWorkers: 15,
    actualWorkers: 12,
    hoursWorked: 108,
    zone: 'Bâtiment C',
    contact: 'Sophie Leroy — 06 45 67 89 01',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Coulage dalle béton Bât A Niv. 3',
    description: 'Mise en œuvre dalle béton armé C30/37 sur 450m²',
    status: 'in_progress',
    priority: 'high',
    deadline: '15/04/2026',
    assignee: 'EIFFAGE Gros Œuvre',
    progress: 75,
    company: 'co2',
  },
  {
    id: 't2',
    title: 'Pose menuiseries extérieures Bât B',
    description: 'Installation fenêtres et baies vitrées double vitrage',
    status: 'todo',
    priority: 'medium',
    deadline: '30/04/2026',
    assignee: 'BOUYGUES Construction',
    progress: 0,
    company: 'co1',
  },
  {
    id: 't3',
    title: 'Installation réseau électrique Bât A',
    description: 'Câblage tableau général + distribution étages',
    status: 'in_progress',
    priority: 'high',
    deadline: '20/04/2026',
    assignee: 'VINCI Électricité',
    progress: 45,
    company: 'co3',
  },
  {
    id: 't4',
    title: 'Carrelage halls et couloirs Bât C',
    description: 'Pose carrelage grès cérame 60x60 zones communes',
    status: 'done',
    priority: 'low',
    deadline: '15/02/2026',
    assignee: 'GECINA Finitions',
    progress: 100,
    company: 'co4',
  },
  {
    id: 't5',
    title: 'Peinture intérieure Bât B',
    description: 'Enduit + peinture blanche toutes pièces Bât B',
    status: 'delayed',
    priority: 'medium',
    deadline: '10/04/2026',
    assignee: 'BOUYGUES Construction',
    progress: 20,
    company: 'co1',
  },
  {
    id: 't6',
    title: 'Étanchéité toiture Bât C',
    description: 'Mise en œuvre étanchéité bicouche + isolation',
    status: 'todo',
    priority: 'high',
    deadline: '05/05/2026',
    assignee: 'EIFFAGE Gros Œuvre',
    progress: 0,
    company: 'co2',
  },
];

export const MOCK_DOCUMENTS: Document[] = [
  { id: 'd1', name: 'Plan Bâtiment A — Niveau RDC', type: 'plan', category: 'Plans', uploadedAt: '2026-02-01', size: '4.2 Mo', version: 3 },
  { id: 'd2', name: 'Plan Bâtiment A — Niveaux R+1/R+2', type: 'plan', category: 'Plans', uploadedAt: '2026-02-01', size: '5.8 Mo', version: 2 },
  { id: 'd3', name: 'Plan Bâtiment B — Vue générale', type: 'plan', category: 'Plans', uploadedAt: '2026-02-05', size: '3.9 Mo', version: 2 },
  { id: 'd4', name: 'Plan Bâtiment C — Niveaux', type: 'plan', category: 'Plans', uploadedAt: '2026-02-08', size: '4.5 Mo', version: 1 },
  { id: 'd5', name: 'DCE Électricité — Lot 6', type: 'technical', category: 'DCE', uploadedAt: '2026-01-15', size: '2.1 Mo', version: 1 },
  { id: 'd6', name: 'DCE Plomberie — Lot 8', type: 'technical', category: 'DCE', uploadedAt: '2026-01-15', size: '1.8 Mo', version: 1 },
  { id: 'd7', name: 'CCTP Gros Œuvre', type: 'technical', category: 'DCE', uploadedAt: '2026-01-10', size: '3.2 Mo', version: 2 },
  { id: 'd8', name: 'Rapport journalier S12-J1', type: 'report', category: 'Rapports', uploadedAt: '2026-03-23', size: '0.8 Mo', version: 1 },
  { id: 'd9', name: 'Rapport hebdomadaire Semaine 11', type: 'report', category: 'Rapports', uploadedAt: '2026-03-16', size: '1.2 Mo', version: 1 },
  { id: 'd10', name: 'PV Réception Phase 1', type: 'report', category: 'PV', uploadedAt: '2026-02-01', size: '0.5 Mo', version: 1 },
  { id: 'd11', name: 'Fiche technique béton C30/37', type: 'technical', category: 'Fiches', uploadedAt: '2026-01-20', size: '0.3 Mo', version: 1 },
  { id: 'd12', name: "Plan évacuation incendie", type: 'plan', category: 'Sécurité', uploadedAt: '2026-02-10', size: '1.5 Mo', version: 2 },
];

export const MOCK_PHOTOS: Photo[] = [
  { id: 'p1', comment: "Fissure mur porteur — vue d'ensemble", location: 'Bât A, R+2, Zone Sud', takenAt: '2026-03-01 09:15', takenBy: 'J. Dupont', colorCode: '#EF4444' },
  { id: 'p2', comment: 'Avancement coulage dalle niveau 3', location: 'Bât A, R+3', takenAt: '2026-03-20 14:30', takenBy: 'J. Dupont', colorCode: '#3B82F6' },
  { id: 'p3', comment: 'Infiltration toiture bât B', location: 'Bât B, Toiture', takenAt: '2026-03-10 11:00', takenBy: 'M. Martin', colorCode: '#F59E0B' },
  { id: 'p4', comment: 'Pose carrelage hall C — terminé', location: 'Bât C, RDC, Hall', takenAt: '2026-02-14 16:45', takenBy: 'S. Leroy', colorCode: '#10B981' },
  { id: 'p5', comment: 'Installation tableau électrique TG', location: 'Bât A, RDC, Local tech.', takenAt: '2026-03-15 10:00', takenBy: 'P. Bernard', colorCode: '#8B5CF6' },
  { id: 'p6', comment: 'Façade ouest bâtiment B — état actuel', location: 'Bât B, Façade Ouest', takenAt: '2026-03-16 09:30', takenBy: 'M. Martin', colorCode: '#F97316' },
  { id: 'p7', comment: 'Joints façade manquants zone R+1', location: 'Bât B, R+1, Façade', takenAt: '2026-03-15 15:20', takenBy: 'J. Dupont', colorCode: '#EF4444' },
  { id: 'p8', comment: 'Avancement chantier vue globale', location: 'Vue générale', takenAt: '2026-03-25 08:00', takenBy: 'J. Dupont', colorCode: '#FF6B2B' },
];

export const MOCK_MESSAGES: Message[] = [
  { id: 'm1', channelId: 'general', sender: 'Système', content: 'Réserve RSV-001 créée — Fissure mur porteur Niveau 2 [CRITIQUE]', timestamp: '01/03/2026 08:30', type: 'notification', read: true, isMe: false, reactions: {}, isPinned: false, readBy: [], mentions: [] },
  { id: 'm2', channelId: 'general', sender: 'Marc Martin', content: "Bonjour, les travaux de reprise toiture sont planifiés pour lundi. L'équipe sera sur site à 7h30.", timestamp: '10/03/2026 09:15', type: 'message', read: true, isMe: false, reactions: {}, isPinned: false, readBy: [], mentions: [] },
  { id: 'm3', channelId: 'general', sender: 'Moi', content: "Parfait. N'oubliez pas le rapport photo avant/après.", timestamp: '10/03/2026 09:22', type: 'message', read: true, isMe: true, reactions: {}, isPinned: false, readBy: [], mentions: [] },
  { id: 'm4', channelId: 'general', sender: 'Système', content: 'RSV-003 passée en statut "Vérification" par Paul Bernard', timestamp: '18/03/2026 14:10', type: 'notification', read: true, isMe: false, reactions: {}, isPinned: false, readBy: [], mentions: [] },
  { id: 'm5', channelId: 'general', sender: 'Paul Bernard', content: 'CONSUEL prévu jeudi après-midi pour validation installation électrique bât A.', timestamp: '18/03/2026 16:00', type: 'message', read: false, isMe: false, reactions: {}, isPinned: false, readBy: [], mentions: [] },
  { id: 'm6', channelId: 'general', sender: 'Sophie Leroy', content: 'Attention, la livraison du carrelage prévu lundi est repoussée au mercredi. Impact sur RSV-004.', timestamp: '22/03/2026 07:45', type: 'message', read: false, isMe: false, reactions: {}, isPinned: false, readBy: [], mentions: [] },
  { id: 'm7', channelId: 'general', sender: 'Système', content: 'RSV-007 créée — Porte coupe-feu CF60 non installée [CRITIQUE] — Échéance : 10/04/2026', timestamp: '20/03/2026 11:30', type: 'notification', read: false, isMe: false, reactions: {}, isPinned: false, readBy: [], mentions: [] },
  { id: 'm8', channelId: 'general', sender: 'Moi', content: "Réunion chantier mercredi 9h30 en base vie. Présence obligatoire des chefs d'équipe.", timestamp: '25/03/2026 08:15', type: 'message', read: true, isMe: true, reactions: {}, isPinned: false, readBy: [], mentions: [] },
];
