// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/plans-buildings/BottomSheet.tsx": () => import("../components/mockups/plans-buildings/BottomSheet.tsx"),
  "./components/mockups/plans-buildings/RecentsHybrid.tsx": () => import("../components/mockups/plans-buildings/RecentsHybrid.tsx")
};
