-- Final private-media cutover guardrails.
--
-- This migration is deliberately additive: it can be deployed while the
-- legacy buckets are still public. The service-only finalizer will refuse to
-- flip them private unless every tenant-owned current reference is registered
-- and linked, the compatible Android build is known, and the legacy public R2
-- Worker has been retired.

create table if not exists private.media_cutover_quarantine (
  id bigint generated by default as identity primary key,
  organization_id uuid,
  provider text,
  bucket text,
  object_key text,
  resource_type text,
  resource_id text,
  slot text,
  media_ref text,
  reason text not null,
  first_observed_at timestamptz not null default now(),
  last_observed_at timestamptz not null default now(),
  resolved_at timestamptz
);

create unique index if not exists media_cutover_quarantine_identity_idx
  on private.media_cutover_quarantine(
    coalesce(organization_id::text, ''),
    coalesce(provider, ''),
    coalesce(bucket, ''),
    coalesce(object_key, ''),
    coalesce(resource_type, ''),
    coalesce(resource_id, ''),
    coalesce(slot, ''),
    reason
  );

revoke all on table private.media_cutover_quarantine from public, anon, authenticated;

create or replace function private.current_media_references()
returns table (
  organization_id uuid,
  resource_type text,
  resource_id text,
  slot text,
  media_ref text
)
language sql
stable
set search_path = ''
as $$
  select p.organization_id, 'photos', p.id::text, 'uri', p.uri
  from public.photos p where nullif(btrim(p.uri), '') is not null
  union all
  select d.organization_id, 'documents', d.id::text, 'uri', d.uri
  from public.documents d where nullif(btrim(d.uri), '') is not null
  union all
  select p.organization_id, 'site_plans', p.id::text, 'uri', p.uri
  from public.site_plans p where nullif(btrim(p.uri), '') is not null
  union all
  select d.organization_id, 'regulatory_docs', d.id::text, 'uri', d.uri
  from public.regulatory_docs d where nullif(btrim(d.uri), '') is not null
  union all
  select i.organization_id, 'incidents', i.id::text, 'photo_uri', i.photo_uri
  from public.incidents i where nullif(btrim(i.photo_uri), '') is not null
  union all
  select p.organization_id, 'inventory_products', p.id::text, 'photo_url', p.photo_url
  from public.inventory_products p where nullif(btrim(p.photo_url), '') is not null
  union all
  select v.organization_id, 'visites', v.id::text, 'cover_photo_uri', v.cover_photo_uri
  from public.visites v where nullif(btrim(v.cover_photo_uri), '') is not null
  union all
  select m.organization_id, 'messages', m.id::text, 'attachment_uri', m.attachment_uri
  from public.messages m where nullif(btrim(m.attachment_uri), '') is not null
  union all
  select r.organization_id, 'reserves', r.id::text, 'photo_uri', r.photo_uri
  from public.reserves r where nullif(btrim(r.photo_uri), '') is not null
  union all
  select r.organization_id,
         'reserves',
         r.id::text,
         'photos:' || item.ordinality::text,
         item.value ->> 'uri'
  from public.reserves r
  cross join lateral jsonb_array_elements(
    case when jsonb_typeof(r.photos) = 'array' then r.photos else '[]'::jsonb end
  ) with ordinality as item(value, ordinality)
  where nullif(btrim(item.value ->> 'uri'), '') is not null
$$;

revoke all on function private.current_media_references() from public, anon, authenticated;

create or replace function private.media_cutover_preflight()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with refs as (
    select r.*,
           case
             when r.media_ref ~ '^btmedia://[0-9a-fA-F-]{36}$'
               then substring(r.media_ref from 11)::uuid
             else null
           end as requested_asset_id,
           p.provider as parsed_provider,
           p.bucket as parsed_bucket,
           p.object_key as parsed_object_key
    from private.current_media_references() r
    left join lateral private.media_url_parts(r.media_ref) p on true
  ), hosted as (
    select r.*,
           a.id as matched_asset_id,
           a.status as matched_asset_status,
           exists (
             select 1
             from public.tenant_media_links l
             where l.asset_id = a.id
               and l.organization_id = r.organization_id
               and l.resource_type = r.resource_type
               and l.resource_id = r.resource_id
           ) as has_resource_link
    from refs r
    left join public.tenant_media_objects a
      on a.organization_id = r.organization_id
     and (
       (r.requested_asset_id is not null and a.id = r.requested_asset_id)
       or (
         r.requested_asset_id is null
         and r.parsed_provider is not null
         and a.provider = r.parsed_provider
         and a.bucket = r.parsed_bucket
         and a.object_key = r.parsed_object_key
       )
     )
    where r.requested_asset_id is not null or r.parsed_provider is not null
  ), counts as (
    select
      count(*) filter (where organization_id is not null) as owned_hosted_refs,
      count(*) filter (where organization_id is null) as tenantless_hosted_refs,
      count(*) filter (
        where organization_id is not null
          and (
            matched_asset_id is null
            or matched_asset_status not in ('ready', 'legacy')
            or not has_resource_link
          )
      ) as unresolved_owned_refs
    from hosted
  ), registry as (
    select
      count(*) filter (
        where a.status in ('ready', 'legacy')
          and not exists (
            select 1 from public.tenant_media_links l where l.asset_id = a.id
          )
      ) as unlinked_registry_assets,
      count(*) filter (where a.provider = 'r2' and a.status = 'legacy') as legacy_r2_assets
    from public.tenant_media_objects a
  ), object_store as (
    select count(*) as unregistered_supabase_objects
    from storage.objects o
    where o.bucket_id in ('photos', 'documents')
      and not exists (
        select 1
        from public.tenant_media_objects a
        where a.provider = 'supabase'
          and a.bucket = o.bucket_id
          and a.object_key = o.name
          and a.status <> 'deleted'
      )
  ), buckets as (
    select
      count(*) as bucket_count,
      count(*) filter (where b.public) as public_bucket_count
    from storage.buckets b
    where b.id in ('photos', 'documents')
  )
  select jsonb_build_object(
    'ready',
      c.unresolved_owned_refs = 0
      and r.unlinked_registry_assets = 0
      and b.bucket_count = 2,
    'owned_hosted_refs', c.owned_hosted_refs,
    'unresolved_owned_refs', c.unresolved_owned_refs,
    'tenantless_hosted_refs', c.tenantless_hosted_refs,
    'unlinked_registry_assets', r.unlinked_registry_assets,
    'legacy_r2_assets', r.legacy_r2_assets,
    'unregistered_supabase_objects', o.unregistered_supabase_objects,
    'bucket_count', b.bucket_count,
    'public_bucket_count', b.public_bucket_count,
    'checked_at', now()
  )
  from counts c
  cross join registry r
  cross join object_store o
  cross join buckets b
$$;

revoke all on function private.media_cutover_preflight() from public, anon, authenticated;

-- Tenantless legacy rows and unreferenced storage objects are intentionally
-- quarantined instead of being guessed into an organization. The latter will
-- become inaccessible at cutover but are not deleted by this migration.
insert into private.media_cutover_quarantine(
  organization_id, provider, bucket, object_key,
  resource_type, resource_id, slot, media_ref, reason
)
select r.organization_id,
       p.provider,
       p.bucket,
       p.object_key,
       r.resource_type,
       r.resource_id,
       r.slot,
       r.media_ref,
       'tenantless_current_reference'
from private.current_media_references() r
left join lateral private.media_url_parts(r.media_ref) p on true
where r.organization_id is null
  and (
    r.media_ref ~ '^btmedia://[0-9a-fA-F-]{36}$'
    or p.provider is not null
  )
on conflict (
  (coalesce(organization_id::text, '')),
  (coalesce(provider, '')),
  (coalesce(bucket, '')),
  (coalesce(object_key, '')),
  (coalesce(resource_type, '')),
  (coalesce(resource_id, '')),
  (coalesce(slot, '')),
  reason
)
do update set last_observed_at = now(), media_ref = excluded.media_ref;

insert into private.media_cutover_quarantine(
  provider, bucket, object_key, reason
)
select 'supabase', o.bucket_id, o.name, 'unregistered_storage_object'
from storage.objects o
where o.bucket_id in ('photos', 'documents')
  and not exists (
    select 1
    from public.tenant_media_objects a
    where a.provider = 'supabase'
      and a.bucket = o.bucket_id
      and a.object_key = o.name
      and a.status <> 'deleted'
  )
on conflict (
  (coalesce(organization_id::text, '')),
  (coalesce(provider, '')),
  (coalesce(bucket, '')),
  (coalesce(object_key, '')),
  (coalesce(resource_type, '')),
  (coalesce(resource_id, '')),
  (coalesce(slot, '')),
  reason
)
do update set last_observed_at = now();

create or replace function public.server_get_private_media_cutover_preflight()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select private.media_cutover_preflight()
$$;

revoke all on function public.server_get_private_media_cutover_preflight()
  from public, anon, authenticated;
grant execute on function public.server_get_private_media_cutover_preflight()
  to service_role;

-- Safe, deliberately small runtime payload for mobile clients. No registry
-- key, tenant metadata or quarantine detail is exposed.
create or replace function public.get_client_security_requirements()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select jsonb_build_object(
    'private_media_storage', coalesce(f.enabled, false),
    'phase', coalesce(f.details ->> 'phase', 'dual_read'),
    'minimum_android_build', coalesce(
      case
        when (f.details ->> 'minimum_android_build') ~ '^[0-9]+$'
          then (f.details ->> 'minimum_android_build')::integer
        else 0
      end,
      0
    ),
    'minimum_media_protocol', coalesce(
      case
        when (f.details ->> 'minimum_media_protocol') ~ '^[0-9]+$'
          then (f.details ->> 'minimum_media_protocol')::integer
        else 1
      end,
      1
    ),
    'minimum_client_version', f.details ->> 'minimum_client_version',
    'download_url', 'https://github.com/Admin-Adher/ApplicationMobile/releases/latest/download/buildtrack-release.apk'
  )
  from (select 1) seed
  left join private.runtime_security_flags f on f.flag = 'private_media_storage'
$$;

revoke all on function public.get_client_security_requirements() from public;
grant execute on function public.get_client_security_requirements() to anon, authenticated, service_role;

-- Disable the earlier two-argument finalizer so the R2-retirement and numeric
-- build gates cannot be bypassed accidentally.
create or replace function public.server_finalize_private_media_storage(
  p_minimum_client_version text,
  p_confirm boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  raise exception 'Use the guarded four-argument private-media finalizer'
    using errcode = '0A000';
end;
$$;

create or replace function public.server_finalize_private_media_storage(
  p_minimum_client_version text,
  p_minimum_android_build integer,
  p_public_r2_retired boolean,
  p_confirm boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_version text := nullif(btrim(p_minimum_client_version), '');
  v_preflight jsonb;
begin
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('buildtrack.private_media_cutover', 0)
  );

  if p_confirm is not true
     or v_version is null
     or coalesce(p_minimum_android_build, 0) <= 0
     or p_public_r2_retired is not true then
    raise exception 'Explicit confirmation, compatible build, and retired public R2 are required'
      using errcode = '22023';
  end if;

  v_preflight := private.media_cutover_preflight();
  if coalesce((v_preflight ->> 'ready')::boolean, false) is not true then
    raise exception 'Private-media preflight failed: %', v_preflight::text
      using errcode = '55000';
  end if;

  update storage.buckets
  set public = false
  where id in ('photos', 'documents');

  if (select count(*) from storage.buckets b where b.id in ('photos', 'documents') and not b.public) <> 2 then
    raise exception 'Both BuildTrack media buckets must exist and be private'
      using errcode = '55000';
  end if;

  insert into private.runtime_security_flags(flag, enabled, details, updated_at, updated_by)
  values (
    'private_media_storage',
    true,
    jsonb_build_object(
      'phase', 'private',
      'minimum_client_version', v_version,
      'minimum_android_build', p_minimum_android_build,
      'minimum_media_protocol', 1,
      'public_r2_retired', true,
      'activated_at', now(),
      'preflight', v_preflight
    ),
    now(),
    auth.uid()
  )
  on conflict (flag) do update
  set enabled = excluded.enabled,
      details = excluded.details,
      updated_at = excluded.updated_at,
      updated_by = excluded.updated_by;

  return jsonb_build_object(
    'enabled', true,
    'minimum_client_version', v_version,
    'minimum_android_build', p_minimum_android_build,
    'minimum_media_protocol', 1,
    'public_r2_retired', true,
    'buckets', jsonb_build_array('photos', 'documents'),
    'preflight', v_preflight
  );
end;
$$;

revoke all on function public.server_finalize_private_media_storage(text, boolean)
  from public, anon, authenticated;
revoke all on function public.server_finalize_private_media_storage(text, integer, boolean, boolean)
  from public, anon, authenticated;
grant execute on function public.server_finalize_private_media_storage(text, boolean)
  to service_role;
grant execute on function public.server_finalize_private_media_storage(text, integer, boolean, boolean)
  to service_role;

notify pgrst, 'reload schema';
